### ISSUE TITLE
Stuck at "Cluster the sky model" step

### ISSUE THREAD

**Issue by AlexKurek** [mhardcastle/ddf-pipeline#250] opened 2021-08-05 08:47 UTC
Im trying to process a 25 SB L232875 dataset. Im using manually compiled Singularity container based on https://github.com/tikk3r/lofar-grid-hpccloud . One thing I had to change was to add:
```
echo "IgnoreDeprecationMarking = 1" >> $INSTALLDIR/DDFacet/lib/python2.7/site-packages/DDFacet/Parset/DefaultParset.cfg
echo "IgnoreDeprecationMarking = 1" >> $INSTALLDIR/DDFacet/src/DDFacet/Parset/DefaultParset.cfg
```
At the beginning it works smoothly even though I still see one occurrence of:

> /opt/lofar/DDFacet/bin/DDF.py:409: DeprecationWarning: Python 2 has reached end of life and is no longer supported. You can continue running the software in Python 2 (along with other deprecated modes) by setting --Misc-IgnoreDeprecationMarking in your parset. No further Python 2 related bug fixes or support is available.

in the log. But later:

```
[91m============================== Cluster the sky model =============================[0m

[92mRunning: MakeCatalog.py --RestoredIm image_dirin_SSD_m.app.restored.fits --rmsmean_map [Noise.mean.fits,Noise.fits][0m
 - 22:44:21 - MakeCatalog        | [1m[92mFile image_dirin_SSD_m.app.restored.fits exist[0m[0m
[1;34m--> Opened 'image_dirin_SSD_m.app.restored.fits'[0m
Image size .............................. : (19845, 19845) pixels
Number of channels ...................... : 1
Number of Stokes parameters ............. : 1
Beam shape (major, minor, pos angle) .... : (3.33333e-03, 3.33333e-03, 90.0) degrees
Frequency of image ...................... : 144.627 MHz
Number of blank pixels .................. : 0 (0.0%)
Flux from sum of (non-blank) pixels ..... : 101.633 Jy
[1;34m--> Calculating background rms and mean images[0m
[1;34m--> Skipping mean and rms image computation as external images supplied[0m
[1;34m-->    Opening mean image: Noise.mean.fits[0m
[1;34m--> Opened 'Noise.mean.fits'[0m
[1;34m-->    Opening rms image: Noise.fits[0m
[1;34m--> Opened 'Noise.fits'[0m
[1;34m--> Variation in rms image significant[0m
[1;34m--> Using 2D map for background rms[0m
[1;34m--> Variation in mean image not significant[0m
[1;34m--> Using constant background mean[0m
Min/max values of background rms map .... : (1.94e-04, 1.86e-02) Jy/beam
Value of background mean ................ : -1e-05 Jy/beam
[1;34m--> Expected 5-sigma-clipped false detection rate < fdr_ratio[0m
[1;34m--> Using sigma-clipping ('hard') thresholding[0m
Minimum number of pixels per island ..... : 24
Number of islands found ................. : 1918
```
and later htop shows that CPU usage is 0% for all cores but still 5.79 GB od RAM is reserved. I was able to process the same dataset using older containers based of private branches. Full log is attached.
[logBash.zip](https://github.com/mhardcastle/ddf-pipeline/files/6937235/logBash.zip)

**Comment by mhardcastle** [comment] 2021-08-05 15:25
So the clustering is using PyBDSF and there are various PyBDSF bugs that can cause a hang like this. Do you know which version of PyBDSF is used in the container and is it possible to use the latest git master (where I pushed some bug fixes not long ago)?

**Comment by mhardcastle** [comment] 2021-08-05 19:01
Could be a regression -- if so I would be interested in seeing the image that triggers it.

Let us know how you get on.

**Comment by AlexKurek** [comment] 2021-08-06 08:30
A lot of images were produced before it stucked. Do you want me to upload any of them?

> image_dirin_SSD.alpha.fits
> image_dirin_SSD.app.restored.fits
> image_dirin_SSD.app.restored.fits.mask.fits
> image_dirin_SSD.brutalModelConv01.fits
> image_dirin_SSD.brutalRestored01.fits
> image_dirin_SSD.DicoFacet
> image_dirin_SSD.DicoModel
> image_dirin_SSD.facetCoord.psf.txt
> image_dirin_SSD.facetCoord.txt
> image_dirin_SSD.fluxscale.fits
> image_dirin_SSD_init.DicoFacet
> image_dirin_SSD_init.dirty.corr.fits
> image_dirin_SSD_init.dirty.fits
> image_dirin_SSD_init.facetCoord.psf.txt
> image_dirin_SSD_init.facetCoord.txt
> image_dirin_SSD_init.log
> image_dirin_SSD_init.NodesCat.npy
> image_dirin_SSD_init.NormFacets.fits
> image_dirin_SSD_init.Norm.fits
> image_dirin_SSD_init.parset
> image_dirin_SSD_init.psf.DicoFacet
> image_dirin_SSD_init.psf.fits
> image_dirin_SSD_init.tessel.psf.reg
> image_dirin_SSD_init.tessel.reg
> image_dirin_SSD.int.model.fits
> image_dirin_SSD.int.residual.fits
> image_dirin_SSD.int.restored.fits
> image_dirin_SSD.labelIslands01.fits
> image_dirin_SSD.log
> image_dirin_SSD_m.01.DicoModel
> image_dirin_SSD_m.alpha.fits
> image_dirin_SSD_m.app.restored.fits
> image_dirin_SSD_m.app.restored.fits.pybdsf.log
> image_dirin_SSD.mask01.fits
> image_dirin_SSD_m.brutalModelConv01.fits
> image_dirin_SSD_m.brutalModelConv02.fits
> image_dirin_SSD_m.brutalRestored01.fits
> image_dirin_SSD_m.brutalRestored02.fits
> image_dirin_SSD_m.DicoFacet
> image_dirin_SSD_m.DicoModel
> image_dirin_SSD_m.facetCoord.psf.txt
> image_dirin_SSD_m.facetCoord.txt
> image_dirin_SSD_m.fluxscale.fits
> image_dirin_SSD_m.int.model.fits
> image_dirin_SSD_m.int.residual.fits
> image_dirin_SSD_m.int.restored.fits
> image_dirin_SSD_m.labelIslands01.fits
> image_dirin_SSD_m.labelIslands02.fits
> image_dirin_SSD_m.log
> image_dirin_SSD_m.mask01.fits
> image_dirin_SSD_m.mask02.fits
> image_dirin_SSD_m.model01.fits
> image_dirin_SSD_m.model02.fits
> image_dirin_SSD_m.NodesCat.npy
> image_dirin_SSD_m.noise01.fits
> image_dirin_SSD_m.noise02.fits
> image_dirin_SSD.model01.fits
> image_dirin_SSD_m.parset
> image_dirin_SSD_m.psf.DicoFacet
> image_dirin_SSD_m.residual01.fits
> image_dirin_SSD_m.residual02.fits
> image_dirin_SSD_m.tessel.psf.reg
> image_dirin_SSD_m.tessel.reg
> image_dirin_SSD.NodesCat.npy
> image_dirin_SSD.noise01.fits
> image_dirin_SSD.parset
> image_dirin_SSD.psf.DicoFacet
> image_dirin_SSD.residual01.fits
> image_dirin_SSD.residual01.fits.mask.fits
> image_dirin_SSD.tessel.psf.reg
> image_dirin_SSD.tessel.reg

**Comment by mhardcastle** [comment] 2021-08-06 08:39
The key image is `image_dirin_SSD_m.app.restored.fits`.

**Comment by AlexKurek** [comment] 2021-08-06 08:52
Here it is:
https://www.dropbox.com/s/p5gafrhvqclby82/image_dirin_SSD_m.app.restored.fits?dl=0
I tried to compile the container against PyBDSF 1.9.2, but the compilation crashes at PyBDSF (sth wrong with Numpy). Then I tried PyBDSF commit:
https://github.com/lofar-astron/PyBDSF/commit/36e4c79348b644897edc5d2c0672a50711430fda
but it still ends up being stucked. Now Im trying commit dbfca486752faf2021310f33a5ee8f706bbb95b5, with was just before working version of container ( https://lofar-webdav.grid.sara.nl/software/lofar_sksp_fedora27_ddf_slurmfix.sif?action=show ) was compiled.

**Comment by AlexKurek** [comment] 2021-08-06 11:49
The same thing happened, it stucked, just the number of island id different:

> Minimum number of pixels per island ..... : 24
> Number of islands found ................. : 19

**Comment by mhardcastle** [comment] 2021-08-06 12:05
I'll try to look into it. I looked at your file but there is nothing wrong there (indeed of course we know the pipeline works on this field!). I will check that I can run MakeCatalog on that image manually and let you know, then we may be hunting for some kind of incompatibility or regression. I am about to go for a week's holiday but will work on this when I can.

**Comment by AlexKurek** [comment] 2021-08-17 17:33
BTW, I would have one question. As far as I understand, we - end users - now should use the master branch of DDF. But if I clone master (without checking out DR1) it asks for credentials during installation of DDFacet.

(Im asking because Im trying to make my own Singularity recipe where everything that makes any computations (FFTW, PyFFTW, MKL, CUDA, OpenBLAS, Armadillo, HDF5, SuperLU) is compiled manually using GCC-11, so I could check if it speeds up the entire pipeline)

**Comment by mhardcastle** [comment] 2021-08-17 19:56
(Sorry, internet on the week's leave was not good enough to work on the actual issue.)

The instructions need to be updated here. You should be able to check out the publicly accessible DDFacet versions from the saopicc/DDFacet repository (and they will likely work with ddf-pipeline) rather than cloning from the development repo (cyriltasse).

I don't at the moment know whether the publicly accessible version of killMS is up-to-date enough to run the DR2 pipeline -- possibly not. Worth trying though.

**Comment by AlexKurek** [comment] 2021-08-18 12:14
I did:
`sed -i "s%cyriltasse/DDFacet.git%saopicc/DDFacet.git%g" "install.sh"`
and it passed the step it previously crashed at. Later I also had to do:
`sed -i "s%cp ddf-pipeline%cp ..%g" "install.sh"`
to change this line: https://github.com/mhardcastle/ddf-pipeline/blob/master/scripts/install.sh#L18 , otherwise there was file not found error.
Now it cannot find PyBind11, dependency of DDFacet. I tried via pip and `apt-get install pybind11-dev`, but this I think I will be able to work out.

**Comment by AlexKurek** [comment] 2021-08-28 13:20
I just tired to process also L232877 - also using manually compiled Singularity container based on https://github.com/tikk3r/lofar-grid-hpccloud . The same thing happened, it stuck at "Cluster the sky model" step.

**Comment by mhardcastle** [comment] 2021-11-05 17:40
We could now try this with the python3 singularity that is documented in the master branch? Note that I am still waiting for some bug fixes in public killms to be released but that should not affect this problem.

**Comment by AlexKurek** [comment] 2021-11-06 07:46
I just tried. It seems the environment is not complete:

> [91mYou need to define the environment variable DDF_PIPELINE_CATALOGS where your catalogs are located[0m
> Traceback (most recent call last):
>   File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 1924, in <module>
>     main(o)
>   File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 984, in main
>     die("You need to define the environment variable DDF_PIPELINE_CATALOGS where your catalogs are located")
>   File "/usr/local/src/ddf-pipeline/utils/auxcodes.py", line 51, in die
>     raise Exception(s)
> Exception: You need to define the environment variable DDF_PIPELINE_CATALOGS where your catalogs are located

**Comment by mhardcastle** [comment] 2021-11-06 09:14
That has to point to the path used for automasking/bootstrap catalogues and so is user-defined outside the singularity environment (as are a few other environment variables).

**Comment by AlexKurek** [comment] 2021-11-06 09:56
I solved it like in the attachment. For now its working
[ddf-py3.zip](https://github.com/mhardcastle/ddf-pipeline/files/7490194/ddf-py3.zip)

**Comment by mhardcastle** [comment] 2021-11-06 10:42
OK. Should be a user-defined option with --env in the singularity call.

**Comment by mhardcastle** [comment] 2021-11-06 10:43
(since in general a user might choose to bootstrap with any set of catalogues...)

**Comment by AlexKurek** [comment] 2021-11-06 10:46
It crashed:

> Traceback (most recent call last):
>   File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 1924, in <module>
>     main(o)
>   File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 1139, in main
>     CurrentBaseDicoModelName=ddf_image('image_dirin_SSD_m',o['mslist'],
>   File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 343, in ddf_image
>     run(runcommand,dryrun=options['dryrun'],log=logfilename('DDF-'+imagename+'.log',options=options),quiet=options['quiet'])
>   File "/usr/local/src/ddf-pipeline/utils/auxcodes.py", line 69, in run
>     die('FAILED to run '+s+': return value is '+str(retval))
>   File "/usr/local/src/ddf-pipeline/utils/auxcodes.py", line 51, in die
>     raise Exception(s)
> Exception: FAILED to run DDF.py --Output-Name=image_dirin_SSD_m --Data-MS=mslist.txt --Deconv-PeakFactor 0.001000 --Data-ColName CORRECTED_DATA --Parallel-NCPU=28 --Beam-CenterNorm=1 --Deconv-CycleFactor=0 --Deconv-MaxMinorIter=1000000 --Deconv-MaxMajorIter=2 --Deconv-Mode SSD --Beam-Model=LOFAR --Beam-LOFARBeamMode=A --Weight-Robust -0.150000 --Image-NPix=20000 --CF-wmax 50000 --CF-Nw 100 --Output-Also onNeds --Image-Cell 1.500000 --Facets-NFacets=11 --SSDClean-NEnlargeData 0 --Freq-NDegridBand 1 --Beam-NBand 1 --Facets-DiamMax 1.5 --Facets-DiamMin 0.1 --Deconv-RMSFactor=0.000000 --SSDClean-ConvFFTSwitch 10000 --Data-Sort 1 --Cache-Dir=. --Cache-DirWisdomFFTW=. --Debug-Pdb=never --Log-Memory 1 --GAClean-RMSFactorInitHMP 1.000000 --GAClean-MaxMinorIterInitHMP 10000.000000 --DDESolutions-SolsDir=SOLSDIR --Cache-Weight=reset --Misc-IgnoreDeprecationMarking=1 --Beam-At=facet --Output-Mode=Clean --Predict-ColName DD_PREDICT --Output-RestoringBeam 12.000000 --Weight-ColName="None" --Freq-NBand=2 --RIME-DecorrMode=FT --SSDClean-SSDSolvePars [S,Alpha] --SSDClean-BICFactor 0 --Mask-Auto=1 --Mask-SigTh=15.00 --Mask-External=image_dirin_SSD.app.restored.fits.mask.fits --Predict-InitDicoModel=image_dirin_SSD.DicoModel --Selection-UVRangeKm=[0.100000,1000.000000] --Cache-Dirty forceresidual --Cache-PSF force --GAClean-MinSizeInit=10: return value is 1

**Comment by mhardcastle** [comment] 2021-11-06 10:47
Need to see the DDF error itself, or end of logfile, please.

**Comment by AlexKurek** [comment] 2021-11-06 10:53
[logBash.zip](https://github.com/mhardcastle/ddf-pipeline/files/7490277/logBash.zip)
[logs.zip](https://github.com/mhardcastle/ddf-pipeline/files/7490278/logs.zip)
Oh right, all logs are attached.

**Comment by mhardcastle** [comment] 2021-11-06 10:56
Is this a restart from an earlier run with an earlier ddf-pipeline/python environment?

**Comment by AlexKurek** [comment] 2021-11-06 11:11
It is a restart, but the environment is defined anew, since I have everything in the container.
I deleted all files and folders produced by the pipeline, generated mslists also anew and now Im trying again.

**Comment by AlexKurek** [comment] 2021-11-06 13:22
The same thing happened. This is a result of env insider the container:
> DDF_PIPELINE_CATALOGS=/usr/local/src/DDFCatalogues
> DDF_DIR=/usr/local/src
> KILLMS_DIR=/usr/local/src
> SSH_CONNECTION=149.156.70.216 49434 149.156.70.246 22
> LESSCLOSE=/usr/bin/lesspipe %s %s
> XDG_SESSION_CLASS=user
> PYTHONPATH=/usr/local/src/lotss-hba-survey:/usr/local/src/lotss-query:/usr/local/src/ddf-pipeline/scripts:/usr/local/src/ddf-pipeline/utils:
> TERM=xterm
> LC_IDENTIFICATION=pl_PL.UTF-8
> LESSOPEN=| /usr/bin/lesspipe %s
> USER=akurek
> SHLVL=2
> LC_TELEPHONE=pl_PL.UTF-8
> LC_MEASUREMENT=pl_PL.UTF-8
> SINGULARITY_BIND=
> XDG_SESSION_ID=38
> LD_LIBRARY_PATH=:/usr/local/lib/:/usr/local/idg/lib/:/.singularity.d/libs
> XDG_RUNTIME_DIR=/run/user/1414
> PS1=Singularity>
> SSH_CLIENT=149.156.70.216 49434 22
> LC_TIME=pl_PL.UTF-8
> XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
> PATH=/usr/local/src/killMS/killMS:/usr/local/src/lotss-hba-survey:/usr/local/src/ddf-pipeline/scripts:/usr/local/src/DynSpecMS:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1414/bus
> MKL_NUM_THREADS=1
> SSH_TTY=/dev/pts/0
> SINGULARITY_COMMAND=shell
> LC_NUMERIC=pl_PL.UTF-8
> OLDPWD=/home/akurek
> _=/usr/bin/env

**Comment by mhardcastle** [comment] 2021-11-06 13:39
So still sticking at the cluster the sky model step? Well, at least that proves that we should both be able to see the problem!

So now you have access to the Herts cluster please put mslist.txt and the 6 MSs listed there in a directory on /beegfs/lofar and I will reproduce the problem and see if I can fix it.

**Comment by AlexKurek** [comment] 2021-11-06 14:05
What I meant is that this happened again:
https://github.com/mhardcastle/ddf-pipeline/issues/250#issuecomment-962432964
Im tarring the MSs and will upload soon

**Comment by mhardcastle** [comment] 2021-11-06 14:07
Oh OK. Thanks, this may be a DDF bug of some kind. I have several test runs with the new singularity image that have got past this early point though.

**Comment by AlexKurek** [comment] 2021-11-06 14:11
Still tarring, but just to show you - Im always using DDF exactly like this:
```
singularity exec -B /L343256_new_DDF/results/ ddf-py3.singularity.sif make_mslists.py
singularity exec -B /L343256_new_DDF/results/ ddf-py3.singularity.sif pipeline.py tier1-jul2018.cfg >logBash.txt 2>&1
```
so no external environment should be present for DDF.

**Comment by AlexKurek** [comment] 2021-11-06 19:00
Its uploaded here: /beegfs/lofar/alexkurek/ file archive.tar.gz

**Comment by mhardcastle** [comment] 2021-11-07 19:04
I'm not modifying the main pipeline at the moment so that commit shouldn't be relevant. But my test run on your data using the same singularity image has passed the point where yours crashed and is still running fine. See contents of /beegfs/car/mjh/akurek .

I am starting to wonder a little bit about the integrity of your physical storage (with this and the corrupted MSes).

**Comment by mhardcastle** [comment] 2022-03-27 11:43
No traffic here for a while, closing this issue, reopen again if needed.

**Closed by mhardcastle** 2022-03-27 11:43 UTC
