### ISSUE TITLE
Image_ampphase_di weight issue with new DDFacet/kMS

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#335] opened 2023-11-03 09:44 UTC
Hi,

In ticket https://github.com/mhardcastle/ddf-pipeline/issues/311 we identified that image_ampphase_di in the new kms/ddfacet software is significantly worse than the image_amphase  image.

This seems to be an issue with the weights that come from the DI kMS calibration before the image_ampphase_di step.

To demonstrate this I have done a run where I exited the pipeline (run with the new software) straight after the image_ampphase_di step. The resulting image is:

/beegfs/car/shimwell/Cyril-tests/NEW/P269+63-NEW_NOBOOT_EXITAFTER/image_ampphase1_di.app.restored.fits

I then ran a test in where I changed the weights in the msfiles to be the weights from the DD calibration before the image_ampphase step. I then ran exactly the same imaging step to produce the image_ampphase1_di.app.restored.fits. I.e. the only difference between the images is the weights in the msfiles. The new image from this test that uses DD instead of DI weights is:

/beegfs/car/shimwell/Cyril-tests/NEW/P269+63-NEW_NOBOOT_EXITAFTER/TESTING/image_ampphase1_di_DDWEIGHT.app.restored.fits

As you can see from the comparison (screenshot below where right is the original image_ampphase_di image and left is the one with the DD weights but exactly the same imaging commands) the DI weights seem to be the cause of our problems.

<img width="619" alt="Screenshot 2023-11-03 at 10 44 08" src="https://github.com/mhardcastle/ddf-pipeline/assets/12065270/9eb49fce-ad94-49d7-8598-211c74ab68aa">

**Comment by twshimwell** [comment] 2023-11-08 08:58
Oh nice. Yes makes a lot of sense.

**Comment by twshimwell** [comment] 2023-11-08 09:06
After our discussion yesterday I was trying the pipeline with the DI solves using UpdateWeights=0

Surprisingly though I get an error at the following DI image step. In this case the image_dirin_SSD_di. The error is:

 - 09:04:30 - AsyncProcessPool             [0.9/3.9 59.2/59.2 61.8Gb] FFT: 96 jobs complete, average single-core time 7.22s per job
 - 09:04:30 - ClassFacetMachine            [0.9/3.9 59.2/59.2 61.8Gb]   Building Facet-normalisation image
 - 09:04:30 - DDFacet                      [0.9/3.9 60.7/60.7 61.8Gb] Traceback (most recent call last):
  File "/usr/local/src/DDFacet/DDFacet/DDF.py", line 457, in <module>
    main(OP, messages)
  File "/usr/local/src/DDFacet/DDFacet/DDF.py", line 291, in main
    Imager.main()
  File "/usr/local/src/DDFacet/DDFacet/Imager/ClassDeconvMachine.py", line 1130, in main
    self.GiveDirty(psf=True, sparsify=sparsify, last_cycle=(NMajor==0))
  File "/usr/local/src/DDFacet/DDFacet/Imager/ClassDeconvMachine.py", line 764, in GiveDirty
    self.DicoDirty = self.FacetMachine.FacetsToIm(NormJones=True)
  File "/usr/local/src/DDFacet/DDFacet/Imager/ClassFacetMachine.py", line 1239, in FacetsToIm
    self.BuildFacetNormImage()
  File "/usr/local/src/DDFacet/DDFacet/Imager/ClassFacetMachine.py", line 1493, in BuildFacetNormImage
    SpacialWeigth = self._CF[iFacet]["SW"].T[::-1, :]
  File "/usr/local/src/DDFacet/DDFacet/Array/shared_dict.py", line 237, in __getitem__
    value = collections.OrderedDict.__getitem__(self, item)
KeyError: 'SW'
 - 09:04:30 - DDFacet                      [0.9/3.9 59.2/60.7 61.8Gb] There was a problem after 2m4.2s; if you think this is a bug please open an issue, 
 - 09:04:30 - DDFacet

**Comment by cyriltasse** [comment] 2023-11-08 09:14
Weird - this is a run from scratch? Removing all .ddfcache directories?

**Comment by twshimwell** [comment] 2023-11-08 09:19
Yeh but i did take a couple of shortcuts like removing the columns from msfiles in a n existing run and copying in some of the image products. I just looked and the imaging_weights are all 0. Maybe ive messe things up. I'll start again propoerly

**Comment by cyriltasse** [comment] 2023-11-08 09:21
If the problem is actually the one I described above it's quite funny... How fixing a bug can make things worse :)

**Comment by twshimwell** [comment] 2023-11-08 09:25
Haha yes indeed. No more bug fixes when things eventually work :)

**Comment by twshimwell** [comment] 2023-11-13 14:15
A pull request has been put in (https://github.com/mhardcastle/ddf-pipeline/pull/336) to fix this issue.

**Comment by mhardcastle** [comment] 2023-11-13 15:10
PR merged!

**Closed by mhardcastle** 2023-11-13 15:10 UTC
