### ISSUE TITLE
quality_pipeline astropy error

### ISSUE THREAD

**Issue by wllwen007** [mhardcastle/ddf-pipeline#148] opened 2019-01-16 15:14 UTC
@mhardcastle  I'm trying to run the quality pipeline on the gama fields at Herts and am getting an astropy error in an add_facet_labels step (traceback below). It looks like a numpy issue in this version (noted in astropy: https://github.com/astropy/astropy/issues/7051) 

As for the rest of the ddf-pipeline, I'm using your numpy (v 1.14.0) and astropy (v 2.0.2), both sourced from /home/mjh/.local/lib/python2.7/site-packages 

> Traceback (most recent call last):
  File "/home/mjh/pipeline-master/ddf-pipeline/scripts/quality_pipeline.py", line 182, in <module>
    t=label_table(t,tesselfile,cra,cdec)
  File "/home/mjh/pipeline-master/ddf-pipeline/utils/facet_offsets.py", line 204, in label_table
    r.add_facet_labels(t)
  File "/home/mjh/pipeline-master/ddf-pipeline/utils/facet_offsets.py", line 149, in add_facet_labels
    dra,ddec=self.coordconv(np.array(t['RA']),np.array(t['DEC']))[1] # strip units
  File "/home/mjh/pipeline-master/ddf-pipeline/utils/facet_offsets.py", line 35, in coordconv
    return (c.ra.value,c.dec.value),[v.value for v in self.cref.spherical_offsets_to(c)]
  File "/home/mjh/.local/lib/python2.7/site-packages/astropy/coordinates/sky_coordinate.py", line 841, in spherical_offsets_to
    acoord = tocoord.transform_to(aframe)
  File "/home/mjh/.local/lib/python2.7/site-packages/astropy/coordinates/sky_coordinate.py", line 481, in transform_to
    new_coord = trans(self.frame, generic_frame)
  File "/home/mjh/.local/lib/python2.7/site-packages/astropy/coordinates/transformations.py", line 1314, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "/home/mjh/.local/lib/python2.7/site-packages/astropy/coordinates/transformations.py", line 1232, in __call__
    newrep = self._apply_transform(fromcoord, M, None)
  File "/home/mjh/.local/lib/python2.7/site-packages/astropy/coordinates/transformations.py", line 1005, in _apply_transform
    rep = rep.transform(matrix)
  File "/home/mjh/.local/lib/python2.7/site-packages/astropy/coordinates/representation.py", line 1110, in transform
    newxyz = np.einsum('...ij,j...->i...', matrix, oldxyz.value)
  File "/home/mjh/.local/lib/python2.7/site-packages/numpy/core/einsumfunc.py", line 1087, in einsum
    einsum_call=True)
  File "/home/mjh/.local/lib/python2.7/site-packages/numpy/core/einsumfunc.py", line 688, in einsum_path
    input_subscripts, output_subscript, operands = _parse_einsum_input(operands)
  File "/home/mjh/.local/lib/python2.7/site-packages/numpy/core/einsumfunc.py", line 432, in _parse_einsum_input
    raise TypeError("For this input type lists must contain "
TypeError: For this input type lists must contain either int or Ellipsis

**Comment by mhardcastle** [comment] 2019-01-16 16:04
Hmm, that's odd, I've run the quality pipeline on hundreds of fields over the past few weeks, including some dec=0 ones, so there must be something about my setup that's different from yours. Let me look at it.

**Comment by mhardcastle** [comment] 2020-04-07 08:42
This wasn't reproduced before or since and is over a year old, so going to close it for tidiness.

**Closed by mhardcastle** 2020-04-07 08:42 UTC
