### ISSUE TITLE
unpack.py decompressed to a strange path 

### ISSUE THREAD

**Issue by agwilber** [mhardcastle/ddf-pipeline#106] opened 2018-09-25 13:39 UTC
After running download_field.py on the next field, I ran unpack.py in the directory with the .tar files. The directory prefactor/results is not created so the .ms files are not located and moved. Instead a weird path is created where the .ms files exist:

ls -1d scratch/*/CREAM*/tm*/Output/*.ms

scratch/26896765.batch.gina.sara.nl/CREAM546331915/tmp.cZb12eVuo1/Output/L654746_SB021_uv.pre-cal_12C11F0A6t_125MHz.pre-cal.ms
scratch/26896765.batch.gina.sara.nl/CREAM546331915/tmp.DCM5qnhVxz/Output/L654746_SB218_uv.pre-cal_12C11F0A6t_166MHz.pre-cal.ms
scratch/26896767.batch.gina.sara.nl/CREAM351022999/tmp.kkfgzW6Ufs/Output/L654746_SB086_uv.pre-cal_12C11F0A6t_138MHz.pre-cal.ms
....
etc ...

**Comment by mhardcastle** [comment] 2018-09-25 13:44
Yeah, I have seen this a few times. It's a problem in the pre-processing which I have told @twshimwell about. If you do `mv scratch/*/*/*/*.ms .` you can proceed with make_mslist.py and so on. Perhaps this is common enough that I should fix unpack.py to check for it...

**Comment by twshimwell** [comment] 2018-09-25 13:45
yeh sorry. This is more in the domain of @apmechev :)

**Comment by agwilber** [comment] 2018-09-25 13:48
Yes, I moved the files and proceeded. Pipeline is running okay. Just wanted to let others know in case it happens again. I will let you know with the next pointing if it does the same.

**Comment by mhardcastle** [comment] 2018-09-26 07:57
@apmechev , the problem is that it's not always the same. Most of the tar files have the structure `prefactor/results/*.ms` , but maybe 5% of the ones I've seen have this `scratch/*/*/*/Output/*.ms` structure. An example is L657138. I think the pipeline can now cope but ideally this would be fixed in future processing.

**Comment by apmechev** [comment] 2018-09-26 08:10
Ah, it probably depends on the version of the pipeline we're using. Once
Tim confirms that the DYSCO compressed data is ok to use I'll compress all
past runs and remove all subdirectories, so that it just extracts to *.ms

**Comment by mhardcastle** [comment] 2018-09-28 11:15
OK, let me know when this happens because I'll have to update the unpacking code. Closing this for the moment, since I think there is a fix in place for now.

**Closed by mhardcastle** 2018-09-28 11:15 UTC
