### ISSUE TITLE
Pipeline crash

### ISSUE THREAD

**Issue by fvitello** [mhardcastle/ddf-pipeline#217] opened 2020-04-28 21:06 UTC
Hi, 

i am trying to run the ddf-pipeline but it crashes after few second with the following log:

` pipeline.py tier1-jul2018-NVSS.cfg 
Welcome to ddf-pipeline, version v2.3-20-gf6882f8
Successful readonly open of default-locked table L696229_SB021_uv.pre-cal_12D9DAE98t_125MHz.pre-cal.ms: 29 columns, 3400018 rows
Running: CleanSHM.py
 - 21:05:59 - ClearSHM           | Clear shared memory
 - 21:05:59 - ClearSHM           | Clear Semaphores
 - 21:05:59 - ClearSHM           | Clear shared dictionaries
Checking for IMAGING_WEIGHT in input MSS
Successful readonly open of default-locked table L696229_SB021_uv.pre-cal_12D9DAE98t_125MHz.pre-cal.ms: 29 columns, 3400018 rows
Table L696229_SB021_uv.pre-cal_12D9DAE98t_125MHz.pre-cal.ms already has imaging weights
Successful readonly open of default-locked table L696229_SB060_uv.pre-cal_12D9DAE98t_132MHz.pre-cal.ms: 29 columns, 3400018 rows
Table L696229_SB060_uv.pre-cal_12D9DAE98t_132MHz.pre-cal.ms already has imaging weights
Successful readonly open of default-locked table L696229_SB104_uv.pre-cal_12D9DAE98t_142MHz.pre-cal.ms: 29 columns, 3400018 rows
Table L696229_SB104_uv.pre-cal_12D9DAE98t_142MHz.pre-cal.ms already has imaging weights
Successful readonly open of default-locked table L696229_SB142_uv.pre-cal_12D9DAE98t_150MHz.pre-cal.ms: 29 columns, 3400018 rows
Table L696229_SB142_uv.pre-cal_12D9DAE98t_150MHz.pre-cal.ms already has imaging weights
Successful readonly open of default-locked table L696229_SB180_uv.pre-cal_12D9DAE98t_158MHz.pre-cal.ms: 29 columns, 3400018 rows
Table L696229_SB180_uv.pre-cal_12D9DAE98t_158MHz.pre-cal.ms already has imaging weights
Successful readonly open of default-locked table L696229_SB218_uv.pre-cal_12D9DAE98t_166MHz.pre-cal.ms: 29 columns, 3400018 rows
Table L696229_SB218_uv.pre-cal_12D9DAE98t_166MHz.pre-cal.ms already has imaging weights

================================================================================= Initial dirty  =================================================================================

Running: DDF.py --Output-Name=image_dirin_SSD_init --Data-MS=mslist.txt --Deconv-PeakFactor 0.050000 --Data-ColName CORRECTED_DATA --Parallel-NCPU=10 --Beam-CenterNorm=1 --Deconv-CycleFactor=0 --Deconv-MaxMinorIter=1000000 --Deconv-MaxMajorIter=0 --Deconv-Mode SSD --Beam-Model=LOFAR --Beam-LOFARBeamMode=A --Weight-Robust -0.150000 --Image-NPix=20000 --CF-wmax 50000 --CF-Nw 100 --Output-Also onNeds --Image-Cell 1.500000 --Facets-NFacets=11 --SSDClean-NEnlargeData 0 --Freq-NDegridBand 1 --Beam-NBand 1 --Facets-DiamMax 1.5 --Facets-DiamMin 0.1 --Deconv-RMSFactor=3.000000 --SSDClean-ConvFFTSwitch 10000 --Data-Sort 1 --Cache-Dir=. --Cache-DirWisdomFFTW=. --Debug-Pdb=never --Log-Memory 1 --GAClean-RMSFactorInitHMP 1.000000 --GAClean-MaxMinorIterInitHMP 10000.000000 --DDESolutions-SolsDir=SOLSDIR --Cache-Weight=reset --Output-Mode=Clean --Output-RestoringBeam 12.000000 --Weight-ColName="None" --Freq-NBand=2 --RIME-DecorrMode=FT --SSDClean-SSDSolvePars [S,Alpha] --SSDClean-BICFactor 0 --Mask-Auto=1 --Mask-SigTh=10.00 --Selection-UVRangeKm=[0.100000,1000.000000] --GAClean-MinSizeInit=10
 - 21:06:01 - AsyncProcessPool   | Fixing parent process to vthread 0
 - 21:06:01 - AsyncProcessPool   | Worker affinities not specified, leaving unset
DDFacet version is 0.5.1.0
Using python package located at: /usr/local/lib/python2.7/dist-packages/DDFacet
Using driver file located at: /usr/local/bin/DDF.py
Traceback (most recent call last):
  File "/usr/local/bin/DDF.py", line 409, in <module>
    DeprecationWarning)
DeprecationWarning: Python 2 has reached end of life and is no longer supported. You can continue running the software in Python 2 (along with other deprecated modes) by setting --Misc-IgnoreDeprecationMarking in your parset. No further Python 2 related bug fixes or support is available.
 - 21:06:03 - ClearSHM           | Clear shared memory
 - 21:06:03 - ClearSHM           | Clear Semaphores
 - 21:06:03 - ClearSHM           | Clear shared dictionaries
FAILED to run DDF.py --Output-Name=image_dirin_SSD_init --Data-MS=mslist.txt --Deconv-PeakFactor 0.050000 --Data-ColName CORRECTED_DATA --Parallel-NCPU=10 --Beam-CenterNorm=1 --Deconv-CycleFactor=0 --Deconv-MaxMinorIter=1000000 --Deconv-MaxMajorIter=0 --Deconv-Mode SSD --Beam-Model=LOFAR --Beam-LOFARBeamMode=A --Weight-Robust -0.150000 --Image-NPix=20000 --CF-wmax 50000 --CF-Nw 100 --Output-Also onNeds --Image-Cell 1.500000 --Facets-NFacets=11 --SSDClean-NEnlargeData 0 --Freq-NDegridBand 1 --Beam-NBand 1 --Facets-DiamMax 1.5 --Facets-DiamMin 0.1 --Deconv-RMSFactor=3.000000 --SSDClean-ConvFFTSwitch 10000 --Data-Sort 1 --Cache-Dir=. --Cache-DirWisdomFFTW=. --Debug-Pdb=never --Log-Memory 1 --GAClean-RMSFactorInitHMP 1.000000 --GAClean-MaxMinorIterInitHMP 10000.000000 --DDESolutions-SolsDir=SOLSDIR --Cache-Weight=reset --Output-Mode=Clean --Output-RestoringBeam 12.000000 --Weight-ColName="None" --Freq-NBand=2 --RIME-DecorrMode=FT --SSDClean-SSDSolvePars [S,Alpha] --SSDClean-BICFactor 0 --Mask-Auto=1 --Mask-SigTh=10.00 --Selection-UVRangeKm=[0.100000,1000.000000] --GAClean-MinSizeInit=10: return value is 1
Traceback (most recent call last):
  File "/opt/ddf-pipeline/scripts/pipeline.py", line 1884, in <module>
    main(o)
  File "/opt/ddf-pipeline/scripts/pipeline.py", line 1069, in main
    apply_weights=o['apply_weights'][0], use_weightspectrum=o['use_weightspectrum'], uvrange=uvrange,catcher=catcher)
  File "/opt/ddf-pipeline/scripts/pipeline.py", line 299, in ddf_image
    run(runcommand,dryrun=options['dryrun'],log=logfilename('DDF-'+imagename+'.log',options=options),quiet=options['quiet'])
  File "/opt/ddf-pipeline/utils/auxcodes.py", line 69, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/opt/ddf-pipeline/utils/auxcodes.py", line 51, in die
    raise Exception(s)
Exception: FAILED to run DDF.py --Output-Name=image_dirin_SSD_init --Data-MS=mslist.txt --Deconv-PeakFactor 0.050000 --Data-ColName CORRECTED_DATA --Parallel-NCPU=10 --Beam-CenterNorm=1 --Deconv-CycleFactor=0 --Deconv-MaxMinorIter=1000000 --Deconv-MaxMajorIter=0 --Deconv-Mode SSD --Beam-Model=LOFAR --Beam-LOFARBeamMode=A --Weight-Robust -0.150000 --Image-NPix=20000 --CF-wmax 50000 --CF-Nw 100 --Output-Also onNeds --Image-Cell 1.500000 --Facets-NFacets=11 --SSDClean-NEnlargeData 0 --Freq-NDegridBand 1 --Beam-NBand 1 --Facets-DiamMax 1.5 --Facets-DiamMin 0.1 --Deconv-RMSFactor=3.000000 --SSDClean-ConvFFTSwitch 10000 --Data-Sort 1 --Cache-Dir=. --Cache-DirWisdomFFTW=. --Debug-Pdb=never --Log-Memory 1 --GAClean-RMSFactorInitHMP 1.000000 --GAClean-MaxMinorIterInitHMP 10000.000000 --DDESolutions-SolsDir=SOLSDIR --Cache-Weight=reset --Output-Mode=Clean --Output-RestoringBeam 12.000000 --Weight-ColName="None" --Freq-NBand=2 --RIME-DecorrMode=FT --SSDClean-SSDSolvePars [S,Alpha] --SSDClean-BICFactor 0 --Mask-Auto=1 --Mask-SigTh=10.00 --Selection-UVRangeKm=[0.100000,1000.000000] --GAClean-MinSizeInit=10: return value is 1`

I have tried to add the following section to the cfg file
[Misc]
IgnoreDeprecationMarking = True

but seems to be ignored.

Can you help me to solve this issue?
Thanks

**Comment by mhardcastle** [comment] 2020-04-29 07:59
This is because DDF.py has been changed to fail if running under Python 2. ddf-pipeline itself supports both Python 2 and Python 3.

I can fix this but it isn't trivial because we need to keep the pipeline working with old versions of DDF for compatibility with LoTSS processing -- so I will need to change the code to query the parset and set this option if present.

Can I check, before I do the work, that you have access to the private killMS repository? Otherwise a ddf-pipeline run with current master and up-to-date DDF will fail at a later stage.

**Comment by fvitello** [comment] 2020-04-29 08:03
Thank you very much. Yes i have access both to DDFacet and killMS private repo.

**Comment by mhardcastle** [comment] 2020-04-29 08:07
Cool. I will try to reproduce the problem and provide a new version of ddf-pipeline today.

**Comment by fvitello** [comment] 2020-04-29 08:09
Again, thank you!
Please, also let me know if is required to use specific branches of DDFacet and killMS.

**Comment by mhardcastle** [comment] 2020-04-29 11:51
OK, could you pull ddf-pipeline branch fix_ddf_deprecation and check that that solves your problem? If it does I will merge into master. I have done a very quick test only.

For python2 running with killMS you should probably use killMS branch FixQ_PowerSmooth . This is what we are using for DR2. The combination of this and a recent master DDF.py is not tested but should probably work and I'd be interested to know if it doesn't.

**Comment by fvitello** [comment] 2020-04-29 12:11
seems to be working, the pipeline is currently running. If it is useful for you i can update if it will conclude or if there are some other issues.
Thank you for the quick fix

**Comment by mhardcastle** [comment] 2020-04-29 12:20
Yes, let's keep this issue open. Once you have one example each of a successful DDFacet and killMS run it will be safe to close it -- the change I made affects killMS too and that's the part I wasn't able to test. killMS will probably run in the next 24 hours.

**Comment by mhardcastle** [comment] 2020-04-30 12:00
@fvitello Could you confirm that killMS is working on your run? I want to merge those changes because we have some new work to do for issue #216 for which they would be useful.

**Comment by fvitello** [comment] 2020-04-30 12:04
@mhardcastle Yes it works.

> 2020-04-30 06:03:07:  - 06:03:07 - DDFacet                   | [11.0/24.8 15.1/46.2 11.4Gb] DDFacet ended successfully after 151m52.2s
2020-04-30 06:03:10: Exception AttributeError: "'NoneType' object has no attribute 'SharedDict'" in <bound method ClassImageDeconvMachine.__del__ of <DDFacet.Imager.MSMF.ClassImageDeconvMachineMSMF.ClassImageDeconvMachine instance at 0x7f9118b77638>> ignored
2020-04-30 06:03:10: Exception AttributeError: "'NoneType' object has no attribute 'SharedDict'" in <bound method ClassImageDeconvMachine.__del__ of <DDFacet.Imager.MSMF.ClassImageDeconvMachineMSMF.ClassImageDeconvMachine instance at 0x7f9139adf950>> ignored
Process terminated with return value 0

**Comment by mhardcastle** [comment] 2020-04-30 12:06
Yeah, I thought I'd pushed a DDF change that fixes that, but either you don't have it or it hasn't been merged yet. Either way, nothing to worry about.

**Closed** 2020-04-30 12:06 UTC
