### ISSUE TITLE
ms2dynspec.py - ValueError: operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by botteon** [mhardcastle/ddf-pipeline#110] opened 2018-10-02 16:14 UTC
hi, ms2dynspec crashed with the following error:

```
Traceback (most recent call last):
  File "/opt/DynSpecMS/ms2dynspec.py", line 122, in <module>  
    main(args)
  File "/opt/DynSpecMS/ms2dynspec.py", line 97, in main
    SaveMachine.PlotSpec()
  File "/opt/DynSpecMS/ClassSaveResults.py", line 113, in PlotSpec
    self.PlotSpecSingleDir(iDir)
  File "/opt/DynSpecMS/ClassSaveResults.py", line 258, in PlotSpecSingleDir
    ax3.fill_between(freqs.ravel(), meanfreq-stdfreq, meanfreq+stdfreq, facecolor='#B6CAC8', edgecolor='none', zorder=-10)
  File "/opt/matplotlib-2.2.2/lib/python2.7/site-packages/matplotlib/__init__.py", line 1855, in inner
    return func(ax, *args, **kwargs)
  File "/opt/matplotlib-2.2.2/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 5092, in fill_between
    map(np.ma.getmask, [x, y1, y2]))
ValueError: operands could not be broadcast together with shapes (460,) (480,)
 - 15:55:52 - ClearSHM                  | Clear shared memory 
 - 15:55:52 - ClearSHM                  | Clear Semaphores
 - 15:55:52 - ClearSHM                  | Clear shared dictionaries
FAILED to run ms2dynspec.py --ms mslist-L602890.txt --data DATA_DI_CORRECTED --model DD_PREDICT --sols DDS3_full_smoothed --rad 2. --image image_full_ampphase_di_m.NS.app.restored.fits --LogBoring 0 --SolsDir SOLSDIR: return value is 1
Traceback (most recent call last):
  File "/opt/ddf-pipeline/scripts/pipeline.py", line 1515, in <module>
    main(o)
  File "/opt/ddf-pipeline/scripts/pipeline.py", line 1419, in main
    run(runcommand,dryrun=o['dryrun'],log=logfilename('ms2dynspec.log'),quiet=o['quiet'])
  File "/opt/ddf-pipeline/utils/auxcodes.py", line 54, in run 
    die('FAILED to run '+s+': return value is '+str(retval))  
  File "/opt/ddf-pipeline/utils/auxcodes.py", line 36, in die 
    raise Exception(s)
Exception: FAILED to run ms2dynspec.py --ms mslist-L602890.txt --data DATA_DI_CORRECTED --model DD_PREDICT --sols DDS3_full_smoothed --rad 2. --image image_full_ampphase_di_m.NS.app.restored.fits --LogBoring 0 --SolsDir SOLSDIR: return value is 1
```

The packages (and versions) installed in our nodes are

```
APLpy==1.1.1
asn1crypto==0.24.0
astropy==2.0.7
astropy-healpix==0.2.1
atomicwrites==1.2.1
attrs==18.2.0
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
bcrypt==3.1.4
bdsf==1.8.14
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
cryptography==2.3.1
cycler==0.10.0
Cython==0.28.5
DDFacet==0.3.4.1
deap==1.2.2
decorator==4.0.6
emcee==2.2.1
enum34==1.1.6
funcsigs==1.0.2
idna==2.7
ipaddress==1.0.22
Jinja2==2.10
kiwisolver==1.0.1
linecache2==1.0.0
MarkupSafe==1.0
matplotlib==2.2.2
more-itertools==4.3.0
MySQL-python==1.2.5
numexpr==2.6.8
numpy==1.15.2
paramiko==2.4.2
pathlib2==2.3.2
pdu==0.0.3
Pillow==3.1.2
pluggy==0.7.1
Polygon2==2.0.8
prettytable==0.7.2
psutil==5.4.7
py==1.6.0
py-cpuinfo==4.0.0
pyasn1==0.4.4
pybind11==2.2.4
pycparser==2.19
pyephem==3.7.6.0
pyFFTW==0.10.4
pyfits==3.5
PyMySQL==0.9.2
PyNaCl==1.3.0
pyparsing==2.2.1
pyrap==0.0.5
pyregion==2.0
Pyste==0.9.10
pytest==3.8.1
-e git+https://github.com/casacore/python-casacore@1419201714f29ef4a7e9381fc19377f0002a1296#egg=python_casacore
python-dateutil==2.7.3
python-monetdb==11.19.3.2
pytz==2018.5
pywcs==1.12
qpid-python==0.22
reproject==0.4
requests==2.19.1
scandir==1.9.0
scipy==1.1.0
Shapely==1.6.4.post2
SharedArray==3.0.0
six==1.10.0
sshtunnel==0.1.4
subprocess32==3.5.2
tables==3.4.4
traceback2==1.4.0
treepick==0.1.4
unittest-xml-reporting==1.5.0
unittest2==1.1.0
urllib3==1.23
wcsaxes==0.9
yorn==0.0.6
```

Note that after the crash I restarted the pipeline and it moved on...
The last files created before the crash are `last_dynspec.obj` `Transient_LOTTS.csv` and `DynSpecs_L602890`

**Comment by mhardcastle** [comment] 2018-10-02 16:20
I think this is caused by a bug in dynspecms which is fixed by a PR I have made to that repository which has not yet been checked by @cyriltasse... if you pull the issue#5 branch of dynspecms and rerun you should be OK, though. Note that you should remove the DynSpecs_L... directory before rerunning the pipeline otherwise the step will just be skipped.

**Comment by mhardcastle** [comment] 2018-10-03 09:28
Since the fix is merged now you should be able to pull on dynspecms master and proceed. Closing this.

**Closed by mhardcastle** 2018-10-03 09:28 UTC
