### ISSUE TITLE
/dev/shm file exists when processing deep fields

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#150] opened 2019-01-26 07:50 UTC
On the image_full_ampphase_di_m.NS imaging step of the deep Lockman field when appending  --Misc-ConserveMemory=1 to the regular ddf-pipeline command I am still hitting memory errors I think. The error log is attached.
[memerror.txt](https://github.com/mhardcastle/ddf-pipeline/files/2798764/memerror.txt)

The node has 128G of swap and 252G of mem. /dev/shm is 225G

**Comment by mhardcastle** [comment] 2019-01-26 08:32
The error message is saying that the 'file' in /dev/shm that backs the shared array already exists when the code tries to create it. If that's correct it's a bug, not a memory error. Does it exist? `/dev/shm/ddf.120890/DeconvListIslands/int:30035:d/str:Island:a`)

I assume /dev/shm was clear when you started the run...

**Comment by twshimwell** [comment] 2019-01-26 12:20
Indeed that file does exist so it must be a bug then i guess.

Yes I rerun making sure /dev/shm was clear and got exactly the same error.

**Comment by twshimwell** [comment] 2019-01-26 17:40
we could try something like that.

Not sure if it offers any clusters but when I ran it again I got different numbers causing the errors:errors.

OSError: [Errno 17] File exists: 'file:///dev/shm/ddf.71849/DeconvListIslands/int:30034:d/str:Island:a'

**Comment by twshimwell** [comment] 2019-01-28 06:59
Same issue on this branch still it seems.

**Comment by mhardcastle** [comment] 2019-01-28 07:39
Well that's the one thing I didn't expect. Can you post the output immediately before the crash?

**Comment by twshimwell** [comment] 2019-01-28 08:19
Here we go.

[write-error.txt](https://github.com/mhardcastle/ddf-pipeline/files/2801982/write-error.txt)

**Comment by twshimwell** [comment] 2019-01-28 08:41
I hadnt recompiled after checking out  ddfp-issue-150. Hopefully thats ok though.

**Comment by mhardcastle** [comment] 2019-01-28 08:47
Should be, I think. Do the following in a python version to check you picked up the new version:
```
from DDFacet.Array import shared_dict
s=shared_dict.SharedDict('test')
d=s.addSubdict(1)
d=s.addSubdict(1)
```
If this gives a warning at the second addSubdict then you're OK.

**Comment by twshimwell** [comment] 2019-01-28 08:50
Just tried those commands and indeed i see the warning.

**Comment by cyriltasse** [comment] 2019-01-28 08:58
Hey guies - sorry just ctching up on this... Can you run `MemMonitor`, it's likely to be a RAM issue (I've seen that before I think)... Can you make sure that your shm is 100% of the RAM too?

**Comment by mhardcastle** [comment] 2019-01-28 08:58
Ah, this is interesting. The error from CreateShared is inside a try/except block that's designed to catch this error already! So why it's not working I don't know. I guess the 'file exists' error does not mean what we think it means.

I've pushed a change to the logic in npshared, you could pull and try again (would be interested if it now produces any log messages... doubt it will actually work...)

**Comment by twshimwell** [comment] 2019-01-28 09:06
OK pulled the latest ddfp-issue-150. Killed everything I have on the node and cleaned the shared memory and started MemMonitor.

/dev/shm has 225G available (there is and there is 252GB ram so /dev/shm is not quite 100% -- you think that could do it?) There are 128G in swap.

**Comment by cyriltasse** [comment] 2019-01-28 09:08
Isn't it supposed to save the island that crashed in the try/except, like a `err_island???.npy` or something? Can you check @twshimwell ?

**Comment by twshimwell** [comment] 2019-01-28 09:14
Its all be deleted now but I can check if this run crashes.

**Comment by mhardcastle** [comment] 2019-01-28 10:34
Just for the record, if I try creating subdicts of an existing dict and filling them with np arrays until I run out of space on /dev/shm, I get the usual bus error, not a file exists.

**Comment by twshimwell** [comment] 2019-01-28 16:00
Its still doing "Creating shared structures for 38731 islands" for 3hrs.

**Comment by twshimwell** [comment] 2019-01-28 17:33
Hmm its still hanging on this step... im sure it doesnt usually take this long. I think perhaps it is hanging although 1 cpu still claims to be churning away.

The MemMonitor output is below. 

<img width="966" alt="screenshot 2019-01-28 18 31 38" src="https://user-images.githubusercontent.com/12065270/51854470-269e8680-232b-11e9-8a26-a4a33257cda2.png">

**Comment by cyriltasse** [comment] 2019-01-28 17:36
Any `errIsland` thin.npy file?

**Comment by twshimwell** [comment] 2019-01-28 17:41
not in the working directory

**Comment by mhardcastle** [comment] 2019-01-28 18:00
If it's hanging that means the try/except thing is being called continuously. Odd that it doesn't produce any logs but you should just kill it...

**Comment by cyriltasse** [comment] 2019-01-28 18:01
Can you point me to the try/except you mean?

**Comment by mhardcastle** [comment] 2019-01-28 20:21
In NpShared.py/CreateShared , line 71 or so.

**Comment by twshimwell** [comment] 2019-01-30 10:06
Perhaps I should move this issue to the ddfacet github?

**Comment by mhardcastle** [comment] 2019-02-01 15:10
Well, we can try to think about it some more here.... I have a bit more time.

The code that it's hanging on is this (in the new branch):

```
def CreateShared(Name, shape, dtype):
    while True:
        try:
            a = SharedArray.create(Name, shape, dtype=dtype)
        except OSError:
            print>> log, ModColor.Str("File %s exists, deleting" % Name)
            DelArray(Name)
        else:
            break
    return a
```

So that means that DelArray is not removing the existing file (which shouldn't exist anyway), OR that the 'file exists' error doesn't actually mean that the file exists, but rather that the code emits that when it runs out of memory for some reason. 

You could test whether it's the latter by letting shm get bigger than physical memory (I presume you have some swap on this machine). If it is the latter it'll get further before it crashes. The idea that it's run out of memory is consistent with the memmonitor plot.

Alternatively, we could try to chunk the parallelization over islands as I suggested on the telecon.

**Comment by cyriltasse** [comment] 2019-02-01 15:14
Humm - why don't we print the actual exception string?

@twshimwell will be in Paris in soon and we can take a look at this together...

**Comment by twshimwell** [comment] 2019-02-01 15:16
I’ll try to get my paws on a node with higher memory and give it a try there in the meantime

**Comment by mhardcastle** [comment] 2019-02-01 15:30
Well the print to log in the exception handler doesn't seem to do anything anyway -- @twshimwell didn't see any output when it was hanging.

**Comment by twshimwell** [comment] 2019-02-01 15:32
When it didn’t hang it did drop into the debugging state if I can do anything from that

**Comment by cyriltasse** [comment] 2019-02-01 15:44
Something like that?

```
            try:
                Whatever
            except Exception,e:
                print "Exception worker: %s"%str(e)
                break
```

**Comment by cyriltasse** [comment] 2019-02-12 09:37
ok - the true error seems to be 

`*** OSError: [Errno 12] Cannot allocate memory`

The error message is super misleading here:

https://github.com/cyriltasse/DDFacet/blob/4180f5ee585a71d6d6786efb7470e013da3519ac/DDFacet/Array/NpShared.py#L73

**Comment by mhardcastle** [comment] 2019-02-12 11:36
Tim, did you make your shm correspondingly bigger on the bigger machine?

**Comment by twshimwell** [comment] 2019-02-12 11:54
yeh when i used the bigger machine /dev/shm was 450GB

**Comment by cyriltasse** [comment] 2019-02-13 09:40
Ok, I've reproduced the bug on the bigger node:

```
 - 19:33:12 - ClassImageDeconvMachine   | [36.3/109.9 51.0/131.3 83.6Gb] Evolving 50 generations of 50 sourcekin
 - 19:33:12 - ClassImageDeconvMachine   | [36.3/109.9 51.0/131.3 83.6Gb] Deconvolve small islands (<=10000 pixels) (parallelised over island)
DDFacet has encountered an unexpected error. Dropping you into pdb for a post-mortem.
(This is because you're running with --Debug-Pdb set to 'auto' and --Log-Boring is off.)
Traceback (most recent call last):
  File "/net/para10/data1/shimwell/software/killmsddf/new-install//DDFacet/DDFacet/DDF.py", line 387, in <module>
    main(OP, messages)
  File "/net/para10/data1/shimwell/software/killmsddf/new-install//DDFacet/DDFacet/DDF.py", line 235, in main
    Imager.main()
  File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Imager/ClassDeconvMachine.py", line 1097, in main
    repMinor, continue_deconv, update_model = self.DeconvMachine.Deconvolve()
  File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Imager/SSD/ClassImageDeconvMachineSSD.py", line 410, in Deconvolve
    self.DeconvListIsland(ListSmallIslands,ParallelMode="OverIslands",ListInitIslands=ListInitSmallIslands)
  File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Imager/SSD/ClassImageDeconvMachineSSD.py", line 490, in DeconvListIsland
    island_dict["Island"] = np.array(ThisPixList)
  File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Array/shared_dict.py", line 255, in __setitem__
    value = NpShared.ToShared(_to_shm(path+'a'), value)
  File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Array/NpShared.py", line 87, in ToShared
    a = CreateShared(Name, A.shape, A.dtype)
  File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Array/NpShared.py", line 71, in CreateShared
    a = SharedArray.create(Name, shape, dtype=dtype)
OSError: [Errno 12] Cannot allocate memory: 'file:///dev/shm/ddf.17238/DeconvListIslands/int:30034:d/str:Island:a'

```

Then in the debugger, I cannot create any `sharedarray`, but I can create numpy arrays.

```
(Pdb) Aa = SharedArray.create("test",(10,10),np.complex128)   
*** OSError: [Errno 12] Cannot allocate memory: 'test'
(Pdb) Aa=np.ones((10,10),np.complex128)
(Pdb) 
```

While there is still plenty of available memory

```
shimwell@lofar4 ALL-DATA]$ df -h /dev/shm
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           475G   84G  392G  18% /dev/shm

```

Talking to Mat @mat@ampyxpower.com he made me check a few things


```
[shimwell@lofar4 ALL-DATA]$ cat /proc/sys/kernel/shmmax
18446744073692774399
[shimwell@lofar4 ALL-DATA]$ cat /proc/sys/kernel/shmall
18446744073692774399
[shimwell@lofar4 ALL-DATA]$ cat /proc/sys/kernel/shmmni
4096
```

and he thought changing `shmmni` could help

`sudo sysctl -w kernel.shmmni=32768`

@twshimwell can you have one of the root run this on `lofar4`?

**Comment by nudomarinero** [comment] 2019-02-13 21:40
If the filesystem runs out of i-nodes the errors raised by the OS are exactly the same as if it runs out of space. I hope the shmmni reconfiguration works but, if not, it could be interesting to check the number of free i-nodes with ```du -i /dev/shm```

**Comment by cyriltasse** [comment] 2019-02-14 00:04
That's what it says

```
[shimwell@lofar4 ALL-DATA]$ du -i /dev/shm
du: invalid option -- 'i'
Try 'du --help' for more information.
```

**Comment by nudomarinero** [comment] 2019-02-14 07:09
I am sorry @cyriltasse I meant ```df -i /dev/shm```.

**Comment by cyriltasse** [comment] 2019-02-14 09:56
```
[shimwell@lofar4 ALL-DATA]$ df -i /dev/shm
Filesystem       Inodes  IUsed    IFree IUse% Mounted on
tmpfs          66017838 118214 65899624    1% /dev/shm
```

**Comment by cyriltasse** [comment] 2019-02-14 10:01
Still crashing at the same place after the `sudo sysctl -w kernel.shmmni=32768`

**Comment by ampyx-mat** [comment] 2019-02-14 10:13
Are you maybe trying to open more than 1024 files? The typical max number of file descriptors per process on Linux is 1024, and you can bump it to 4096 without having to be root.

In python:
> import resource
> resource.setrlimit(resource.RLIMIT_NOFILE, (4096,4096))

**Comment by cyriltasse** [comment] 2019-02-14 10:25
I should do this in the parent script `DDF.py`?

**Comment by ampyx-mat** [comment] 2019-02-14 10:27
I don't know how your code is organised, but this 1024 limit is per process. In doubt I'd do it in every process until you can nail down which one exceeds the limit (assuming that this is really the issue).

**Comment by o-smirnov** [comment] 2019-02-14 10:35
@cyriltasse asked me to subscribe. I don't know what's going on, but I'd like to.

**Comment by cyriltasse** [comment] 2019-02-14 10:37
Rerunning with @ampyx-mat suggestion

**Comment by cyriltasse** [comment] 2019-02-14 14:06
@ampyx-mat nope - it doesn't help...

**Comment by cyriltasse** [comment] 2019-02-14 14:09
There are 93155 files in `/dev/shm/ddf.48657`

```
[shimwell@lofar4 ALL-DATA]$ find /dev/shm/ddf.48657 | wc -l
93155
```

**Comment by cyriltasse** [comment] 2019-02-14 15:30
While not killing this process, in another interpreter

```
NFiles=100000
for iFile in range(NFiles):
    ...:     print iFile
    ...:     A=DDFacet.Array.NpShared.SharedArray.create("file:///dev/shm/ddf.48657/DeconvListIslands/int:29995:d/str:BestIndiv:abb%i"%iFile, (4,), dtype=np.float32)
    ...:     A+=1
```

works like a charm. WTF?... Anybody?

**Comment by cyriltasse** [comment] 2019-02-14 15:31
Closed by mistake obviously

**Comment by ampyx-mat** [comment] 2019-02-14 16:07
@cyriltasse can you check using regular files instead of SHM objects? You can prefix the array name with "file://" followed by the full path. Try this on a real partition rather than on a tmpfs.

Also you can try to play with the "vm.max_map_count" kernel parameter that controls the maximum number of maps per process. Each SharedArray uses one map, and it looks like you like big numbers :)

From the shell:
> $ sysctl vm.max_map_count
> vm.max_map_count = 65530
> $ sudo sysctl vm.max_map_count=655300
> vm.max_map_count = 655300

**Comment by cyriltasse** [comment] 2019-02-14 16:15
Thanks @ampyx-mat for all the advices.

The arrays names are always prefixed with `file://`

```
  File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Array/NpShared.py", line 71, in CreateShared
    a = SharedArray.create(Name, shape, dtype=dtype)
OSError: [Errno 12] Cannot allocate memory: 'file:///dev/shm/ddf.48657/DeconvListIslands/int:29995:d/str:BestIndiv:a'

```

Trying your first command:

`bash: sysctl: command not found...`

**Comment by cyriltasse** [comment] 2019-02-14 16:17
`systemctl` maybe?

**Comment by ampyx-mat** [comment] 2019-02-14 16:19
Try `/sbin/sysctl`, or `cat /proc/sys/vm/max_map_count`. Note that you need to be root to change it.

**Comment by cyriltasse** [comment] 2019-02-14 16:21
ok thanks that works... @twshimwell can you have an admin do  

`sudo /sbin/sysctl vm.max_map_count=655300`

**Comment by twshimwell** [comment] 2019-02-14 16:23
ok ive asked

**Comment by twshimwell** [comment] 2019-02-15 07:54
admin have made this change for you now @cyriltasse

**Comment by cyriltasse** [comment] 2019-02-15 11:10
Hey hey - I think it works!!! I'm gonna let the run continue before being too happy bit it used to crash before the step it's at now!

**Comment by o-smirnov** [comment] 2019-02-15 11:12
So what was the problem? Was it the ``vm.max_map_count`` setting? We need to put that into the README (along with them SHM_SIZE advise) if so.

**Comment by cyriltasse** [comment] 2019-02-15 11:14
Yeah it seems to be the `sudo /sbin/sysctl vm.max_map_count=655300` - let's see if it finishes... but it's definitly encouraging!

**Comment by cyriltasse** [comment] 2019-02-15 11:14
Maybe it's something for the `SharedArray` documentation too

**Comment by ampyx-mat** [comment] 2019-02-15 11:16
@cyriltasse Yeah I'll add it to the `README.md` file of SharedArray if it indeed does fix your issue.

**Comment by cyriltasse** [comment] 2019-02-15 13:54
Ok - well - all our gratitude to @ampyx-mat , always to have him onboard! 

To make this permanent `echo 655300 > /proc/sys/vm/max_map_count` ?

**Comment by ampyx-mat** [comment] 2019-02-15 14:34
No worries. To make it permanent you need to add `vm.max_map_count = 655300` to `/etc/sysctl.conf`. By the way you may want to tweak the 655300 number, I just multiplied the previous value by 10 because I'm too lazy to read manuals.

**Comment by cyriltasse** [comment] 2019-02-15 14:39
ok @ampyx-mat - and if tu te sors les doigts du c.. what number does it give?

**Comment by ampyx-mat** [comment] 2019-02-15 14:55
@cyriltasse alright.. so the reason the original value is suspiciously close to 64k but not exactly 64k is explained in a nice comment in the kernel source file `include/mm.h`:
```c
/*
 * Default maximum number of active map areas, this limits the number of vmas
 * per mm struct. Users can overwrite this number by sysctl but there is a
 * problem.
 *
 * When a program's coredump is generated as ELF format, a section is created
 * per a vma. In ELF, the number of sections is represented in unsigned short.
 * This means the number of sections should be smaller than 65535 at coredump.
 * Because the kernel adds some informative sections to a image of program at
 * generating coredump, we need some margin. The number of extra sections is
 * 1-3 now and depends on arch. We use "5" as safe margin, here.
 *
 * ELF extended numbering allows more than 65535 sections, so 16-bit bound is
 * not a hard limit any more. Although some userspace tools can be surprised by
 * that.
 */
#define MAPCOUNT_ELF_CORE_MARGIN	(5)
#define DEFAULT_MAX_MAP_COUNT	(USHRT_MAX - MAPCOUNT_ELF_CORE_MARGIN)
```
So it looks like you could set it to anything really, the worst that can happen is that some old tools might be confused when looking at core dumps. I'd go with some power of two, like 1048576 (2^20).

Now, where was I with my fingers...

**Comment by cyriltasse** [comment] 2019-02-15 15:25
All right - very satisfacory to get to the bottom of things. Thanks again @ampyx-mat !

**Closed by cyriltasse** 2019-02-15 15:25 UTC
