### ISSUE TITLE
bootstrap crashes

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#87] opened 2018-08-02 11:40 UTC
not nice errors on crashing 

Crossmatch table exists, skipping crossmatch
About to fit to 53 data points
Fitting 1 scale factors
emcee: Exception while calling your likelihood function:
  params: [0.86549192]
  args: (array([7.40000000e+07, 3.27000000e+08, 1.18260193e+08]), array([[ 0.76261878,  0.1476    ,  1.        ],
       [ 2.54674745,  0.621     ,  1.        ],
       [ 1.02228439,  0.3204    ,  1.        ],
       [ 0.61928082,  0.3465    ,  1.        ],
       [ 1.0632478 ,  0.288     ,  1.        ],
       [ 0.72650152,  0.3303    ,  1.        ],
       [ 1.22350931,  0.2709    ,  1.        ],
       [ 1.590523  ,  0.3051    ,  1.        ],
       [ 0.87998194,  0.1575    ,  1.        ],
       [ 0.51840901,  0.0963    ,  1.        ],
       [ 0.8781544 ,  0.1809    ,  1.        ],
       [ 0.76629835,  0.3132    ,  1.        ],
       [ 1.25023139,  0.4401    ,  1.        ],
       [ 0.41409725,  0.3195    ,  1.        ],
       [ 1.0692873 ,  0.324     ,  1.        ],
       [ 1.04710579,  0.2457    ,  1.        ],
       [ 1.0214597 ,  0.4356    ,  1.        ],
       [ 0.46111766,  0.162     ,  1.        ],
       [ 1.2900902 ,  0.3015    ,  1.        ],
       [ 4.09548187,  1.332     ,  1.        ],
       [ 0.60274178,  0.1728    ,  1.        ],
       [ 0.4042173 ,  0.1494    ,  1.        ],
       [ 0.73966318,  0.1431    ,  1.        ],
       [ 1.08068049,  0.459     ,  1.        ],
       [ 2.34297037,  0.5643    ,  1.        ],
       [ 2.1024375 ,  0.5877    ,  1.        ],
       [ 0.59462905,  0.1602    ,  1.        ],
       [ 2.09805942,  0.7425    ,  1.        ],
       [ 0.6656279 ,  0.2034    ,  1.        ],
       [ 2.21504569,  0.4284    ,  1.        ],
       [ 0.3442277 ,  0.126     ,  1.        ],
       [ 1.25725973,  0.3339    ,  1.        ],
       [ 0.52807653,  0.1377    ,  1.        ],
       [ 0.46614489,  0.2016    ,  1.        ],
       [ 1.81276631,  0.5265    ,  1.        ],
       [ 1.24909711,  0.2898    ,  1.        ],
       [ 1.63013208,  0.4446    ,  1.        ],
       [ 1.22646713,  0.3942    ,  1.        ],
       [ 0.9155032 ,  0.3348    ,  1.        ],
       [ 1.3333981 ,  0.4221    ,  1.        ],
       [13.4983263 ,  3.3327    ,  1.        ],
       [ 3.23233461,  0.828     ,  1.        ],
       [ 0.64708143,  0.2817    ,  1.        ],
       [ 0.55193031,  0.0738    ,  1.        ],
       [47.77000809, 15.1992    ,  1.        ],
       [ 1.15826797,  0.2259    ,  1.        ],
       [ 5.4509902 ,  1.4292    ,  1.        ],
       [ 0.63176346,  0.1782    ,  1.        ],
       [ 1.15604687,  0.2682    ,  1.        ],
       [ 0.75832683,  0.3573    ,  1.        ],
       [ 0.5301075 ,  0.1737    ,  1.        ],
       [ 1.02586901,  0.2961    ,  1.        ],
       [ 0.74332023,  0.2088    ,  1.        ]]), array([[9.67118591e-02, 3.14999977e-03, 1.00000000e+06],
       [1.07400320e-01, 2.87999981e-03, 1.00000000e+06],
       [1.12076357e-01, 2.87999981e-03, 1.00000000e+06],
       [9.06117633e-02, 3.14999977e-03, 1.00000000e+06],
       [7.73843899e-02, 2.78999982e-03, 1.00000000e+06],
       [9.09824893e-02, 2.96999980e-03, 1.00000000e+06],
       [1.11919172e-01, 3.14999977e-03, 1.00000000e+06],
       [1.06864989e-01, 3.06000002e-03, 1.00000000e+06],
       [1.08158752e-01, 3.06000002e-03, 1.00000000e+06],
       [6.98849782e-02, 2.78999982e-03, 1.00000000e+06],
       [7.06552193e-02, 2.87999981e-03, 1.00000000e+06],
       [7.55083933e-02, 3.23999976e-03, 1.00000000e+06],
       [9.76929367e-02, 3.06000002e-03, 1.00000000e+06],
       [6.98215812e-02, 2.78999982e-03, 1.00000000e+06],
       [1.05604731e-01, 3.23999976e-03, 1.00000000e+06],
       [1.03702068e-01, 2.87999981e-03, 1.00000000e+06],
       [9.76751968e-02, 3.06000002e-03, 1.00000000e+06],
       [6.23543076e-02, 2.69999984e-03, 1.00000000e+06],
       [1.44712299e-01, 3.14999977e-03, 1.00000000e+06],
       [7.98501372e-02, 3.06000002e-03, 1.00000000e+06],
       [8.83246064e-02, 3.23999976e-03, 1.00000000e+06],
       [7.17746615e-02, 3.23999976e-03, 1.00000000e+06],
       [1.38602480e-01, 3.06000002e-03, 1.00000000e+06],
       [6.69614598e-02, 2.96999980e-03, 1.00000000e+06],
       [1.02518976e-01, 2.87999981e-03, 1.00000000e+06],
       [1.23874724e-01, 3.14999977e-03, 1.00000000e+06],
       [6.24090694e-02, 2.69999984e-03, 1.00000000e+06],
       [8.26540515e-02, 3.32999998e-03, 1.00000000e+06],
       [7.82905072e-02, 2.96999980e-03, 1.00000000e+06],
       [2.44826376e-01, 3.06000002e-03, 1.00000000e+06],
       [6.54552579e-02, 2.61000008e-03, 1.00000000e+06],
       [1.05934814e-01, 3.23999976e-03, 1.00000000e+06],
       [8.63308832e-02, 3.41999973e-03, 1.00000000e+06],
       [7.10514337e-02, 2.78999982e-03, 1.00000000e+06],
       [8.36545825e-02, 3.14999977e-03, 1.00000000e+06],
       [1.29405364e-01, 3.23999976e-03, 1.00000000e+06],
       [1.11864418e-01, 3.14999977e-03, 1.00000000e+06],
       [1.01555556e-01, 3.14999977e-03, 1.00000000e+06],
       [8.11438337e-02, 2.87999981e-03, 1.00000000e+06],
       [1.05834052e-01, 3.32999998e-03, 1.00000000e+06],
       [1.37361318e-01, 3.32999998e-03, 1.00000000e+06],
       [1.03697702e-01, 3.59999994e-03, 1.00000000e+06],
       [1.23149499e-01, 3.41999973e-03, 1.00000000e+06],
       [8.44646394e-02, 3.32999998e-03, 1.00000000e+06],
       [1.08051725e-01, 3.87000013e-03, 1.00000000e+06],
       [1.22464210e-01, 3.14999977e-03, 1.00000000e+06],
       [1.29699782e-01, 3.41999973e-03, 1.00000000e+06],
       [1.15027532e-01, 3.32999998e-03, 1.00000000e+06],
       [9.83026773e-02, 3.59999994e-03, 1.00000000e+06],
       [9.09034982e-02, 3.23999976e-03, 1.00000000e+06],
       [9.77584273e-02, 3.50999995e-03, 1.00000000e+06],
       [8.94907117e-02, 3.41999973e-03, 1.00000000e+06],
       [1.24643080e-01, 3.32999998e-03, 1.00000000e+06]]))
  kwargs: {}
  exception:
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/emcee/ensemble.py", line 505, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/utils/fitting_factors.py", line 49, in lnpost
    return lnprior(scale)+lnlike(scale,frequencies,fluxes,errors)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/utils/fitting_factors.py", line 29, in lnlike
    popt, pcov = curve_fit(pl, frequencies, sf, sigma=ef, p0=[sf[4],-0.8],maxfev=20000)
IndexError: index 4 is out of bounds for axis 0 with size 3
Traceback (most recent call last):
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/bootstrap.py", line 254, in <module>
    run_bootstrap(o)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/bootstrap.py", line 170, in run_bootstrap
    fitting_factors.run_all(1, name=obsid)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/utils/fitting_factors.py", line 110, in run_all
    sampler.run_mcmc(scale, 1000)
  File "build/bdist.linux-x86_64/egg/emcee/sampler.py", line 157, in run_mcmc
  File "build/bdist.linux-x86_64/egg/emcee/ensemble.py", line 198, in sample
  File "build/bdist.linux-x86_64/egg/emcee/ensemble.py", line 382, in _get_lnprob
  File "build/bdist.linux-x86_64/egg/emcee/ensemble.py", line 505, in __call__
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/utils/fitting_factors.py", line 49, in lnpost
    return lnprior(scale)+lnlike(scale,frequencies,fluxes,errors)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/utils/fitting_factors.py", line 29, in lnlike
    popt, pcov = curve_fit(pl, frequencies, sf, sigma=ef, p0=[sf[4],-0.8],maxfev=20000)
IndexError: index 4 is out of bounds for axis 0 with size 3
 - 13:30:57 - ClearSHM                  | Clear shared memory
 - 13:30:57 - ClearSHM                  | Clear Semaphores
 - 13:30:57 - ClearSHM                  | Clear shared dictionaries
FAILED to run bootstrap.py tier1-DR2.cfg: return value is 1
Traceback (most recent call last):
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/pipeline.py", line 1461, in <module>
    main(o)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/pipeline.py", line 987, in main
    run('bootstrap.py '+' '.join(sys.argv[1:]),log=None,dryrun=o["dryrun"])
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/utils/auxcodes.py", line 54, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/utils/auxcodes.py", line 36, in die
    raise Exception(s)
Exception: FAILED to run bootstrap.py tier1-DR2.cfg: return value is 1

**Comment by mhardcastle** [comment] 2018-08-02 11:47
Weird. Can you point me at the files?

**Comment by twshimwell** [comment] 2018-08-02 12:15
here we go.

/disks/paradata/shimwell/LoTSS-DR2/other-fields/A1682

**Comment by mhardcastle** [comment] 2018-08-03 09:49
Yeah, so the issue is this code (originally Wendy's) in bootstrap.py:

```
    obsids = [os.path.basename(ms).split('_')[0] for ms in mslist]
    Uobsid = set(obsids)
```
So because your MSs are not in the form Lxxxxx_SByyy.ms they're being treated as separate observations.
You either need to rename them or we can put in a flag to force it not to try to detect multiple observations.

**Comment by twshimwell** [comment] 2018-08-03 10:03
Thanks. I'll rename which seems easiest.

**Comment by mhardcastle** [comment] 2018-08-03 11:12
Error message improved in d271dc1 . Closing.

**Closed by mhardcastle** 2018-08-03 11:12 UTC
