### ISSUE TITLE
TEC screen fitting with kMS solutions

### ISSUE THREAD

**Issue by rvweeren** [mhardcastle/ddf-pipeline#81] opened 2018-07-12 13:15 UTC
New issue page to post results from Josh's phase screen work.

Varying clocks were removed beforehand.

**Comment by rvweeren** [comment] 2018-07-12 13:22
This was the used command for the solve (done for each 2 MHz block)

kMS.py --MSName my.ms --SolverType KAFCA --PolMode Scalar --BaseImageName image_full_ampphase_di_m.NS --dt 0.133333 --NIterKF 6 --CovQ 0.1 --LambdaKF=0.5 --NCPU 60 --OutSolsName DDjosh --NChanSols 2 --PowerSmooth=1.0 --InCol DATA --Weighting Natural --UVMinMax=0.100000,1000.000000 --SolsDir=SOLSDIRjosh  --BeamMode LOFAR --LOFARBeamMode=A --DDFCacheDir=. --NodesFile image_dirin_SSD_m.npy.ClusterCat.npy --DicoModel image_full_ampphase_di_m.NS.DicoModel

**Comment by Joshuaalbert** [comment] 2018-07-12 13:30
We have done a full phase+amp solve on a dataset with kMS then went back and used this skymodel as input for a phase only solve in kMS. This produces a set of phases (without imposing any tec model). The clock was taken out before. We do the phase only solve on split MSs of 2 1MHz blocks each. 

## Context
I'm doing a bayesian tec screen fit on raw phase solutions. NDPPP only spits out phases after imposing a tec+csp model which biases the model. Ideally, the input would be completely independent phases in time and freq. Note: the use of Kalman filter to generate these phases means there is time dependence imposed, however the fact that it's an optimal linear gaussian estimator means the errors should be unbiased if a proper state transition was used.

Note: Two schools of thought exist. Impose the Bayesian model during the actual solve, or do it after on the gains. They are not equivalent, but under some assumptions can be similar. The fact that we see the below banding in the low-brightness directions shows that imposing the bayesian model from the start would have higher power than post-processing the gains.

## Brightest direction phase comparison to NDPPP
For the brightest direction things line up resaonably well, which is encouraging

![screenshot from 2018-07-12 15-16-19](https://user-images.githubusercontent.com/14807032/42635757-33cae38a-85e7-11e8-97ff-1abaa2b6c44c.png)

## time-freq dependence of brightest direction
Things look nice for the brightest direction.
![screenshot from 2018-07-12 15-17-23](https://user-images.githubusercontent.com/14807032/42635798-545b59e0-85e7-11e8-9b8f-206826eab669.png)

## time-freq dependence of low brightness direction
An immediately noticeable problem is that there appears to be some banding. The MSs were solved independently with bandwidths per MS of 2MHz blocked in two 1MHz intervals. There appears to be an odd banding issue here. Why does every other channel have zero gains? Suppose we would have split into twice as many MSs with 1MHz each. Would this also occur then? Note that there does appear to be some useful infomration here (slight gradients noticeable). The Kalman filter has imposed some temporal smoothness.
![screenshot from 2018-07-12 15-18-00](https://user-images.githubusercontent.com/14807032/42635817-62fab23e-85e7-11e8-884c-b84d5e2f6955.png)

**Comment by Joshuaalbert** [comment] 2018-07-12 13:43
## Amplitude in time-freq for the brightest direction
This fan like pattern must be related to transit timescales. Perhaps the beam? Perhaps a wrong sky model?
![screenshot from 2018-07-12 15-40-34](https://user-images.githubusercontent.com/14807032/42636824-f8d983c8-85e9-11e8-9afd-e87afd0ea546.png)

**Comment by twshimwell** [comment] 2018-07-12 14:03
Possible to show a few more directions? Also might be nice to see the field and the facet layout (perhaps those are online somewhere?) and perhaps e.g. the faintest facet is diverging or something.

**Comment by twshimwell** [comment] 2018-07-12 14:06
Also for the phase plots whats the colour scale? Does it wrap around?

**Comment by Joshuaalbert** [comment] 2018-07-12 14:16
For the phase plots they are hsv, wrapped, -pi to +pi.
@rvweeren can post the facet layout, but yes this only happens in the facets with almost no flux.
Most important is to understand why this frequency banding occurs though. Even in the low brightness directions every other freq has enough signal to produce something.

![screenshot from 2018-07-12 16-14-19](https://user-images.githubusercontent.com/14807032/42638723-aad8208a-85ee-11e8-9574-b08029009615.png)
![screenshot from 2018-07-12 16-14-05](https://user-images.githubusercontent.com/14807032/42638724-aaf7a3d8-85ee-11e8-89b2-342e466b6352.png)
![screenshot from 2018-07-12 16-13-53](https://user-images.githubusercontent.com/14807032/42638725-ab156b5c-85ee-11e8-9364-feb141d4f0ea.png)
![screenshot from 2018-07-12 16-13-39](https://user-images.githubusercontent.com/14807032/42638727-ab325dfc-85ee-11e8-825e-2d122fa5c96c.png)

**Comment by rvweeren** [comment] 2018-07-12 15:05
This is the layout. The banding problem occurs for the facets mostly at the edge.

![fl](https://user-images.githubusercontent.com/3879473/42641794-a521444e-85f5-11e8-9fab-4f474a182aba.jpg)

**Comment by cyriltasse** [comment] 2018-07-12 15:17
So the philosophy of the KF is in principle to give a prior evolution file that is TEC fitted. These off axis facets would be smoothed to zero-phase basically, and the output would be more or less the same. You just don't have much signal there, so it can be healthy. So my first simple question - can you start from TEC-fitted values to get the tec-screen?

Then on the amp structured, it could be an unmodeled source or could be real as well - hard to know. What's really strange to me is the 1/2 patern on all directions - I've never seen that before, is that a plotting problem?...

**Comment by rvweeren** [comment] 2018-07-12 15:22
I doubt it is a plotting issue. The plotting commands are the same (apart from the direction index) and banding does not occur for facets near the center which have plenty of flux (we tried more than one and it really correlates with the location in the field and amount of flux)

Josh make sure you phase reference to some fixed station (just to make sure....)

**Comment by rvweeren** [comment] 2018-07-12 15:25
My suspicion is that if I use --NChanSols 1 and split the observations in 50 blocks of 1 MHz it will disappear.... (instead of 25 block of 2 MHz and --NChanSols 2). Cyril, I could try that if you think this would be a useful test?

**Comment by Joshuaalbert** [comment] 2018-07-12 19:52
@cyriltasse Yes, I can go from tec solved independently per direction and derive a tec screen (more accuractely it's a tec + cs phase as NDPPP produces). That is something I've already done and which we want to avoid now, because such a scheme imposes biases into the final phase screen. It essentially is only valid at the central frequency, and is just plain wrong in many cases (we can show that the chi2 basin of TEC in low signal regime doesn't even have a global minimum in the right place). Another reason to go straight from phases is because my method is invariant to phase wrapping, so it can properly handle wild ionospheres. 

@rvweeren Yes they are all referenced to ant0. Yes, for facets with lots of flux the odd-even banding is less prevalent, however the problem may still be there but less noticeable.

@rvweeren @cyriltasse before simply using --NChanSols 1 and split the observations in 50 blocks of 1 MHz it would be good to understand where this is coming from so that we can rule out that there is not something implicitly wrong. Even in the low signal regime there should still be noisy answers and not entirely flagged channels.

**Comment by cyriltasse** [comment] 2018-07-12 20:07
just for completeness, `NChanSols` is the number of solutions on the frequency axis, not the step...

**Comment by twshimwell** [comment] 2018-07-13 07:56
Perhaps worth plotting this for a few more fields to see if you always see these strange structures.

**Comment by Joshuaalbert** [comment] 2018-07-13 08:45
@rvweeren can you split the MS into 1MHz bins and rerun with Nchansols=1. That way we can continue with my algorithm testing, and at the same time see what happens in the edge case of one block one solve.

**Comment by rvweeren** [comment] 2018-07-13 08:52
Yes, I have it running with 1 MHz blocks and `--NChanSols 1 `

**Comment by twshimwell** [comment] 2018-07-13 08:56
I think important to check that we dont see this behavior on other fields too though because we use NChanSols 2 as a standard and Cyril said he hadnt seen this type of thing before.

**Comment by cyriltasse** [comment] 2018-07-13 08:58
Is it possible that the number of data-channels varies from sols freq-bin to freq-bin?

**Comment by twshimwell** [comment] 2018-07-13 09:12
I think that there are an even number (10sbs) in one of these msfiles so id have thought that NChanSols would put 5 in each sols freq-bin.

**Comment by twshimwell** [comment] 2018-07-13 09:14
You could try plotting these ones /disks/paradata/shimwell/LoTSS-DR1/other-pointings/testing/ongoing-May18runs/L232875_NKF6/L232875_newrestor/SOLSDIR/*/killMS.DDS3_full.sols.npz

**Comment by rvweeren** [comment] 2018-07-13 09:37
Double checked, there are always 10 channels per block (or 5 in my new run).

**Comment by rvweeren** [comment] 2018-07-13 12:40
We can also try on others datasets but that will take more time (we need to get the clocks out for the TEC screen fitting)

**Comment by twshimwell** [comment] 2018-07-13 12:41
Oh I was thinking purely for the plotting to look at the weird solution issue (even the clock isnt removed it would be nice to see that solutions are not weird).

**Comment by rvweeren** [comment] 2018-07-13 13:06
@twshimwell, yes that will be much quicker/easier to test. Will do that on lofar2 as soon as the` --NChanSols 1` solve is done.

**Comment by twshimwell** [comment] 2018-07-14 09:19
thanks. ive tried to give permissions to /disks/paradata/shimwell/LoTSS-DR1/other-pointings/testing/ongoing-May18runs/L232875_NKF6/L232875_newrestor/SOLSDIR

If it doesnt work just copy SOLSDIR, its not so big.

**Comment by Joshuaalbert** [comment] 2018-07-14 11:39
That data set is a little weird. When merging the ms's I get that there are a mismatch in axes:
``` python
INFO: Sorting output axes...
len pol: 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 - Will be: 4
len dir: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 45 1 1 1 45 1 1 1 45 1 - Will be: 45
len ant: 62 62 62 62 62 62 62 62 62 62 62 62 62 62 62 62 62 62 62 62 62 62 62 62 - Will be: 62
len freq: 4 4 4 4 4 4 4 4 4 4 4 4 4 4 1 4 4 4 1 2 2 2 1 2 - Will be: 79
len time: 596 716 716 596 596 511 511 511 447 447 447 447 447 447 480 358 358 326 480 596 596 511 480 511 - Will be: 3434
```
My expectation was that each of those ms's contained a solution for the same axes except for the frequency axis.

**Comment by Joshuaalbert** [comment] 2018-07-14 12:02
Indeed, the mismatch in axes means that the time axis is getting stacked instead of concatenating down the freq axis. Also 99.1% of the phase values are nan's. Do you have another dataset? For example, if I plot the *time-freq* phase for direction 0, and the first 596 timeslices:
![screenshot from 2018-07-14 14-01-50](https://user-images.githubusercontent.com/14807032/42724207-7bf0f090-876e-11e8-89ad-b3686d52ca8a.png)

**Comment by twshimwell** [comment] 2018-07-14 12:06
You are looking at just the DDS3_full sols right? There should be one file in each of the SOLSDIR/msname/ directories.

**Comment by Joshuaalbert** [comment] 2018-07-14 12:34
Yes I exported the *.ms/*full.sols.npz to hdf5, then merged those.

**Comment by twshimwell** [comment] 2018-07-14 12:50
Ah you just want  *.ms/DDS3*full.sols.npz 

The wildcard you pasted would have picked up other solutions (the DI*full* ones) that have just one direction and varying time averaging.

**Comment by Joshuaalbert** [comment] 2018-07-14 12:52
There are still time axis mismatches, so this results in an incorrect merge. Unless all axes are the same except one axis, and concatenation happens down that axis, the merge will fail. Also the losoto h5parm_collector script needs to sort the freq axe as right now it relies on the order of input files. There are things I can fix and get back to you. But I would also request a consistent dataset to plot.

**Comment by Joshuaalbert** [comment] 2018-07-14 12:56
For the moment though, here is a simple inspection. Each subband exported solution, as I mentioned above, has solsets sol000, sol001, and sol002, each with phase000 soltabs. The len of the frequency axis respectively is 2, 1, and 1. Therefore, let's look at the sol000/phase000 for subband '166MHz':
Both freq blocks are there and similar colors. That's nice. However there is only 1 direction in sol000/phase000 so I can't look at other directions. 

![screenshot from 2018-07-14 14-54-14](https://user-images.githubusercontent.com/14807032/42724623-ebe42f82-8775-11e8-84a8-59768aca9b19.png)

**Comment by Joshuaalbert** [comment] 2018-07-14 12:59
@twshimwell Ahh, okay I'll use better wildcard.

**Comment by twshimwell** [comment] 2018-07-14 13:03
Oh weird as the DDS3*full* ones should have been made with the same dt in the solve. 

Ok well maybe these ones instead /disks/paradata/shimwell/LoTSS-DR1/other-pointings/testing/ongoing-May18runs/L639769/SOLSDIR/*/*DDS3_full.sols*npz

**Comment by twshimwell** [comment] 2018-07-14 13:04
Oh just saw you used the new wildcard :) slow typing on my phone

**Comment by Joshuaalbert** [comment] 2018-07-14 13:12
![screenshot from 2018-07-14 15-11-46](https://user-images.githubusercontent.com/14807032/42724740-45d9bd52-8778-11e8-9735-82cf43f7b24c.png)
![screenshot from 2018-07-14 15-11-33](https://user-images.githubusercontent.com/14807032/42724741-45fc3ec2-8778-11e8-80a3-57fd9a127948.png)
![screenshot from 2018-07-14 15-11-21](https://user-images.githubusercontent.com/14807032/42724742-46131b06-8778-11e8-9b1a-58c20d40fbcf.png)
![screenshot from 2018-07-14 15-11-11](https://user-images.githubusercontent.com/14807032/42724743-4633575e-8778-11e8-9fa2-8bba838fe462.png)
![screenshot from 2018-07-14 15-11-02](https://user-images.githubusercontent.com/14807032/42724744-4656ab28-8778-11e8-9aa8-d607175d919d.png)
![screenshot from 2018-07-14 15-10-52](https://user-images.githubusercontent.com/14807032/42724745-46704c54-8778-11e8-9751-3befaf6568a0.png)
![screenshot from 2018-07-14 15-10-42](https://user-images.githubusercontent.com/14807032/42724746-468e8d04-8778-11e8-825e-4511c579f8f8.png)
![screenshot from 2018-07-14 15-10-32](https://user-images.githubusercontent.com/14807032/42724747-46a7b7c0-8778-11e8-8eb1-055cc71393c9.png)
![screenshot from 2018-07-14 15-10-22](https://user-images.githubusercontent.com/14807032/42724748-46c618be-8778-11e8-91ed-47ddca3b2e95.png)
![screenshot from 2018-07-14 15-10-10](https://user-images.githubusercontent.com/14807032/42724749-46eb7e10-8778-11e8-8260-8a4fe81effc9.png)
![screenshot from 2018-07-14 15-09-59](https://user-images.githubusercontent.com/14807032/42724750-47107aee-8778-11e8-993b-adb80bddec78.png)
![screenshot from 2018-07-14 15-09-48](https://user-images.githubusercontent.com/14807032/42724751-47349faa-8778-11e8-8ebd-cfa3e6bf7f15.png)
![screenshot from 2018-07-14 15-09-37](https://user-images.githubusercontent.com/14807032/42724752-47587560-8778-11e8-9146-1931632c30ee.png)
![screenshot from 2018-07-14 15-09-28](https://user-images.githubusercontent.com/14807032/42724753-477e9ad8-8778-11e8-894b-f9bf7f548f1d.png)
![screenshot from 2018-07-14 15-09-17](https://user-images.githubusercontent.com/14807032/42724754-47a2c444-8778-11e8-9c39-61c2648b36d4.png)
![screenshot from 2018-07-14 15-09-06](https://user-images.githubusercontent.com/14807032/42724755-47c6f396-8778-11e8-9cb3-2cca77325986.png)
![screenshot from 2018-07-14 15-08-55](https://user-images.githubusercontent.com/14807032/42724756-47eb38a0-8778-11e8-9117-a5ffb9e69e6f.png)
![screenshot from 2018-07-14 15-08-45](https://user-images.githubusercontent.com/14807032/42724758-481021ec-8778-11e8-8f5e-34cc3140dd74.png)
![screenshot from 2018-07-14 15-08-35](https://user-images.githubusercontent.com/14807032/42724759-4835cec4-8778-11e8-9bc6-caac4ed2911d.png)
![screenshot from 2018-07-14 15-08-19](https://user-images.githubusercontent.com/14807032/42724760-485850a2-8778-11e8-8bdb-98c2b0f49e16.png)

**Comment by twshimwell** [comment] 2018-07-14 13:52
Thanks for plotting these Josh. They look quite sensible then which is very good to see.

**Comment by rvweeren** [comment] 2018-07-14 15:29
@twshimwell, but I only see about 25 solutions along the freq. axis, so this is not a `--NChanSols 2` solve?

**Comment by Joshuaalbert** [comment] 2018-07-14 15:55
@rvweeren Here is the plot of josh50block for the blocks that have finished so far.
This looks much more normal. What is it about the edge case `NChanSols=2`? What does `NChanSols=3` do?
![screenshot from 2018-07-14 17-53-00](https://user-images.githubusercontent.com/14807032/42726088-e6e80742-878e-11e8-8044-01890b74075f.png)

**Comment by rvweeren** [comment] 2018-07-14 16:34
Note that the y-axis is not simply freq here (since the solve is only partly done, there are still gaps). However, I think we can already conclude the banding is gone. (I can try --NChanSols 3, so we get 3 solutions along the freq. axis per ms, but it will take  2 more days or so before the current solve is done)

**Comment by Joshuaalbert** [comment] 2018-07-14 16:56
Yes ^^ however, the blocks are mostly completing in order so they are close to being ordered.
@rvweeren For reference this is the first one (with banding).
![screenshot from 2018-07-14 18-55-53](https://user-images.githubusercontent.com/14807032/42726611-8e6f91f8-8797-11e8-980a-2b3f89426b30.png)

**Comment by twshimwell** [comment] 2018-07-15 07:32
Ah sorry it seems i dont have examples of DD with nchansols >= 2. The ones I sent were indeed nchansols=1 (but was very nice to see they looked ok). In the pipeline are only use nchansols > 1 as a standard for the DI steps.

**Comment by Joshuaalbert** [comment] 2018-07-18 09:50
## This is the result with `NChanSols=1`. 
Some originally good directions like `Dir_31` are now completely failing to solve.
![screenshot from 2018-07-18 11-49-30](https://user-images.githubusercontent.com/14807032/42874153-b4d58a50-8a80-11e8-863e-462697c14fc6.png)

**Comment by Joshuaalbert** [comment] 2018-07-18 09:57
## Amplitude plot
![screenshot from 2018-07-18 11-57-34](https://user-images.githubusercontent.com/14807032/42874590-cd6055f4-8a81-11e8-952b-ff89dcb86811.png)

**Comment by Joshuaalbert** [comment] 2018-07-18 10:03
@cyriltasse can you do a little rooting around in wirtinger to see where the banding comes from? @rvweeren  and I read through the code, and conclude that all the chans are being iterated over, and a possible source of weirdness is in how you propagate sigP or sigQ?? It's not clear at all though, and that's just a guess.

**Comment by rvweeren** [comment] 2018-07-18 10:47
Once I have a node available I will do a quick --NChanSols 4 test to check if there is banding here as well.

**Comment by Joshuaalbert** [comment] 2018-07-18 11:47
## Difference between`NChanSols=1` and `NChanSols=2`

Despite the obvious banding, there is a flip of `pi` for direction 31.

![screenshot from 2018-07-18 13-40-24](https://user-images.githubusercontent.com/14807032/42879249-3f6a61ae-8a90-11e8-8afc-1608bf657164.png)

## If you furthermore restrict to only the non-banded channels
The different should be near zero.

![screenshot from 2018-07-18 13-44-59](https://user-images.githubusercontent.com/14807032/42879432-e0eb457a-8a90-11e8-848e-7494826da85f.png)

**Comment by cyriltasse** [comment] 2018-07-18 12:20
Could we have a quick chat? I'm losing track of what you're doing...

**Comment by rvweeren** [comment] 2018-07-18 19:23
Same problems show up with MergeSols.py and PlotSolsIm.py. Example for direction 5, note the banding in the --NChanSols 2 (bottom) plot.

![figure_dir7](https://user-images.githubusercontent.com/3879473/42902971-a14d3a32-8ad0-11e8-9464-425a4e86cada.png)
![figure_dir7_nchansol2](https://user-images.githubusercontent.com/3879473/42902977-a6bc1c22-8ad0-11e8-8b6d-5982d3caa53b.png)

**Comment by rvweeren** [comment] 2018-07-18 21:22
@cyriltasse, here's the data in Leiden

/net/rijn/data2/rvweeren/LOFARHBA_A665/DR2Josh/

cyrilP126+65BEAM_1_chan40-60.ms
cyrilP126+65BEAM_1_chan40-50.ms
cyrilP126+65BEAM_1_chan50-60.ms

Example (running from the above mentioned directory):

kMS.py --MSName cyrilP126+65BEAM_1_chan50-60.ms --SolverType KAFCA --PolMode Scalar --BaseImageName image_full_ampphase_di_m.NS --dt 0.133333 --NIterKF 6 --CovQ 0.1 --LambdaKF=0.5 --NCPU 32 --OutSolsName DDchan1 --NChanSols 1 --PowerSmooth=1.0 --InCol DATA --Weighting Natural --UVMinMax=0.100000,1000.000000 --SolsDir=SOLSDIRtest  --BeamMode LOFAR --LOFARBeamMode=A --DDFCacheDir=. --NodesFile image_dirin_SSD_m.npy.ClusterCat.npy --DicoModel image_full_ampphase_di_m.NS.DicoModel

**Comment by cyriltasse** [comment] 2018-07-19 11:08
ok - I can reproduce the problem...

**Comment by Joshuaalbert** [comment] 2018-07-19 11:15
@cyriltasse Note that we find two main types of problem. The first is the banding. The second, is that when `NChanSol=1` some channels in e.g. Dir_31 , have different overall temporal evolution from NChanSol=2.

**Comment by cyriltasse** [comment] 2018-07-20 23:14
Sorry - I was working on it the whole day and couldn't find this bug. I'm getting super close though, I'll try to work on it this week-end.

**Comment by rvweeren** [comment] 2018-07-21 09:50
No problem, thanks for digging into it. (for now we'll proceed with the NChanSol=1 run for the screen fitting)

**Comment by cyriltasse** [comment] 2018-07-22 09:21
Hey i've found a number of things. The solutions are not exactly the same, but they're looking similar now. I've changed a few other things that did not look right in the recursion, but so i've created `MergeDDFMAster_FixEvP` so you can test

**Comment by rvweeren** [comment] 2018-07-23 13:05
Josh can you install this in Leiden on one of the lofar nodes? (then I can redo the test)

(https://github.com/cyriltasse/killMS)

**Comment by Joshuaalbert** [comment] 2018-07-23 13:31
@cyriltasse must first give me access to the repo.

**Comment by Joshuaalbert** [comment] 2018-07-23 16:47
@rvweeren In the meantime, you can download the code from git into a zip file and place in your ftp, and I'll grab unzip and install on a node.

**Comment by cyriltasse** [comment] 2018-07-23 22:15
@Joshuaalbert I've added you as collaborator - so you can have access to the kMS repo.

**Comment by Joshuaalbert** [comment] 2018-07-24 10:15
@rvweeren I'm about to board a flight but I started compiling. I'll see what happened when I get wifi again.

**Comment by Joshuaalbert** [comment] 2018-07-24 10:15
@cyriltasse  Thanks

**Comment by cyriltasse** [comment] 2018-09-06 14:11
Yeah i spent quite a while finding this one - would be worth seing if that fixes things...

**Comment by Joshuaalbert** [comment] 2018-09-06 16:16
We'll run it again. Apologies for not doing so earlier.

**Comment by Joshuaalbert** [comment] 2018-09-06 16:18
@rvweeren Can we start NchanSol=4 solve today?

**Comment by rvweeren** [comment] 2018-09-06 20:07
No, I need help from Tim to install this special branch.

**Comment by rvweeren** [comment] 2018-09-10 20:57
@Joshuaalbert, see

/net/rijn/data2/rvweeren/LOFARHBA_A665/DR2Josh/SOLSDIRjoshNChanSolstestsep2018/

(solutions are inside the dir. cyrilP126+65BEAM_1_chan40-60.ms).

This is just for one block with NchanSol=2, so two solutions along the freq. axis. Should be enough to determine if the banding is gone.

**Comment by Joshuaalbert** [comment] 2018-09-11 08:28
This is the phase 
![phase2sep2018](https://user-images.githubusercontent.com/14807032/45347876-64358980-b5ad-11e8-9eac-6b26fa04c463.png)

**Comment by cyriltasse** [comment] 2018-09-11 08:37
Can you plot all antennas for a given direction? With `PlotSolsIm.py`?

**Comment by rvweeren** [comment] 2018-09-11 10:38
I have a solve with more channels running (should be finished by the end of today...)

**Comment by rvweeren** [comment] 2018-09-11 20:33
Now with more solutions along the freq. axis

/net/rijn/data2/rvweeren/LOFARHBA_A665/DR2Josh/SOLSDIRjoshNChanSolstest2sep2018/

**Comment by Joshuaalbert** [comment] 2018-09-18 22:53
Appologies I took so long. This is all the antennas for Dir9. Note some antennas have less noticable banding
![sol000_phase_dir_9](https://user-images.githubusercontent.com/14807032/45720887-47e5ae00-bba6-11e8-8d6d-b6a24a3382af.png)

**Comment by mhardcastle** [comment] 2020-04-07 08:51
Closing this as things have moved on quite a bit, open a new issue if needed.

**Closed by mhardcastle** 2020-04-07 08:51 UTC
