### ISSUE TITLE
GtkWarning: IA__gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

### ISSUE THREAD

**Issue by fvitello** [mhardcastle/ddf-pipeline#125] opened 2018-11-10 10:25 UTC
Hi,

I have tried to run the pipeline with the tier1-jul2018-NVSS.cfg configuration file; but unfortunately  execution stop with the following:

```
2018-11-09 17:38:34:  - 17:38:34 - matplotlib                | CACHEDIR=/home/lofar_oact/.cache/matplotlib
2018-11-09 17:38:34:  - 17:38:34 - matplotlib.font_manager   | Using fontManager instance from /home/lofar_oact/.cache/matplotlib/fontList.json
2018-11-09 17:38:34: /usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
2018-11-09 17:38:34:   warnings.warn(str(e), _gtk.Warning)
2018-11-09 17:38:34: /opt/matplotlib-2.2.3/lib/python2.7/site-packages/matplotlib/backends/backend_gtk.py:58: GtkWarning: IA__gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
2018-11-09 17:38:34:   cursors.MOVE          : gdk.Cursor(gdk.FLEUR),
2018-11-09 17:38:34: Traceback (most recent call last):
2018-11-09 17:38:34:   File "/opt/DDFacet/SkyModel/ClusterCat.py", line 15, in <module>
2018-11-09 17:38:34:     import Sky.ClassClusterDEAP
2018-11-09 17:38:34:   File "/opt/DDFacet/SkyModel/Sky/ClassClusterDEAP.py", line 36, in <module>
2018-11-09 17:38:34:     import ClassMetricDEAP
2018-11-09 17:38:34:   File "/opt/DDFacet/SkyModel/Sky/ClassMetricDEAP.py", line 9, in <module>
2018-11-09 17:38:34:     import pylab
2018-11-09 17:38:34:   File "/opt/matplotlib-2.2.3/lib/python2.7/site-packages/pylab.py", line 1, in <module>
2018-11-09 17:38:34:     from matplotlib.pylab import *
2018-11-09 17:38:34:   File "/opt/matplotlib-2.2.3/lib/python2.7/site-packages/matplotlib/pylab.py", line 252, in <module>
2018-11-09 17:38:34:     from matplotlib import cbook, mlab, pyplot as plt
2018-11-09 17:38:34:   File "/opt/matplotlib-2.2.3/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
2018-11-09 17:38:34:     _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
2018-11-09 17:38:34:   File "/opt/matplotlib-2.2.3/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
2018-11-09 17:38:34:     [backend_name], 0)
2018-11-09 17:38:34:   File "/opt/matplotlib-2.2.3/lib/python2.7/site-packages/matplotlib/backends/backend_gtkagg.py", line 12, in <module>
2018-11-09 17:38:34:     from matplotlib.backends.backend_gtk import (
2018-11-09 17:38:34:   File "/opt/matplotlib-2.2.3/lib/python2.7/site-packages/matplotlib/backends/backend_gtk.py", line 58, in <module>
2018-11-09 17:38:34:     cursors.MOVE          : gdk.Cursor(gdk.FLEUR),
2018-11-09 17:38:34: RuntimeError: could not create GdkCursor object
Process terminated with return value 1

```

Can you help me to understand the issue?

Thanks

**Comment by mhardcastle** [comment] 2018-11-10 10:46
The issue is that @cyriltasse puts pylab imports in code that doesn't need it (-: , and that causes this problem when running on a machine without an X display.

What version of DDFacet are you running?

As a workround you can connect to the machine you're running on with `ssh -X` .

**Comment by fvitello** [comment] 2018-11-12 08:31
The version of my pipeline is v2.1-15-ga3d77aa
It is not easy to do the workaround cause i'm running on a remote cluster and the pipeline run inside a container. 

Thanks

**Comment by mhardcastle** [comment] 2018-11-12 17:06
I meant the version number of DDFacet, not ddf-pipeline. Can you pull a new version of DDFacet? I fixed the problem in the latest version...

**Comment by mhardcastle** [comment] 2018-11-12 17:09
(in principle you may be able to run ddf-pipeline with the --control-pull=True option to force a pull, if you have write access.)

**Comment by fvitello** [comment] 2018-11-14 08:38
I am not able to write into the container and update the DDFacet; but with

> export MPLBACKEND="Agg"


The issue seems to be solved

**Comment by cyriltasse** [comment] 2018-11-14 09:44
Hooo - nice trick! Does that mean  @mhardcastle can stop commenting my pylab imports? :)))

**Comment by mhardcastle** [comment] 2018-11-14 10:01
Haha. Still better if we don't have to keep finding and fixing this issue!

Closing as a workaround had been found and the code is fixed.

**Closed by mhardcastle** 2018-11-14 10:01 UTC
